"""Sarvam speech-to-text and text-to-speech integration."""
import base64
import logging
import os
import tempfile
from typing import Optional

try:
    from sarvamai import SarvamAI
    _SARVAM_AVAILABLE = True
except ImportError:
    SarvamAI = None
    _SARVAM_AVAILABLE = False

logger = logging.getLogger("ip_sakti.asr")

SUPPORTED_ASR_LANGUAGES = ("en", "hi", "te", "ta", "ml")
_LANGUAGE_CODES = {"en": "en-IN", "hi": "hi-IN", "te": "te-IN", "ta": "ta-IN", "ml": "ml-IN"}


def _sarvam_client() -> Optional[object]:
    api_key = os.getenv("SARVAM_API_KEY")
    if not _SARVAM_AVAILABLE or not api_key:
        return None
    return SarvamAI(api_subscription_key=api_key)


def asr_status() -> dict:
    """Report whether Sarvam SDK and credentials are available."""
    configured = _SARVAM_AVAILABLE and bool(os.getenv("SARVAM_API_KEY"))
    return {
        "configured": configured,
        "provider": "sarvam",
        "note": (
            "Sarvam Saaras speech-to-text and Bulbul text-to-speech are configured."
            if configured
            else "Set SARVAM_API_KEY in the environment."
        ),
    }


def _transcribe_via_sarvam(audio_base64: str, audio_format: str) -> Optional[str]:
    """Transcribe one browser recording with Sarvam Saaras v3."""
    client = _sarvam_client()
    if client is None:
        return None

    suffix = "." + (audio_format.lower() or "webm")
    temp_path = None
    try:
        audio_content = base64.b64decode(audio_base64, validate=True)
        with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as audio_file:
            audio_file.write(audio_content)
            temp_path = audio_file.name
        with open(temp_path, "rb") as audio_file:
            response = client.speech_to_text.transcribe(
                file=audio_file, model="saaras:v3", mode="transcribe"
            )
        return response.transcript.strip() or None
    except Exception as error:
        logger.info("Sarvam ASR failed: %r", error)
        return None
    finally:
        if temp_path:
            try:
                os.unlink(temp_path)
            except OSError:
                pass


def synthesize(text: str, language: str = "en", speaker: str = "shubh") -> Optional[str]:
    """Return base64-encoded WAV audio generated by Sarvam Bulbul v3."""
    client = _sarvam_client()
    if client is None or not text.strip() or len(text) > 2500:
        return None
    try:
        response = client.text_to_speech.convert(
            text=text.strip(), model="bulbul:v3",
            language_code=_LANGUAGE_CODES.get(language, "en-IN"), speaker=speaker,
        )
        return "".join(response.audios)
    except Exception as error:
        logger.info("Sarvam TTS failed: %r", error)
        return None


def transcribe(audio_base64: str, source_language: str = "en",
               audio_format: str = "wav", sampling_rate: int = 16000) -> tuple[str, bool]:
    """Return ``(transcript, success)`` without raising into the API handler."""
    if source_language not in SUPPORTED_ASR_LANGUAGES:
        return (
            f"Voice input isn't supported for language '{source_language}' yet.",
            False,
        )

    if not audio_base64 or not audio_base64.strip():
        return "No audio received.", False

    transcript = _transcribe_via_sarvam(audio_base64, audio_format)
    if transcript:
        return transcript, True

    return (
        "Couldn't transcribe that — Sarvam speech-to-text is unavailable or unconfigured "
        "in this environment. You can type your question instead.",
        False,
    )
