const ADMIN_COPY = {
  en: {
    ministryPortal: 'Ministry / Admin Portal',
    accessTitle: 'Ministry / Regulatory Admin Access',
    signIn: 'Sign In',
    registerAdmin: 'Register Admin',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    inviteCode: 'Admin Invite Code',
    namePlaceholder: 'Ministry official name',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'Provided by ministry IT',
    signInAsAdmin: 'Sign In as Admin',
    registerAdminAccount: 'Register Admin Account',
    pleaseWait: 'Please wait...',
    backToCitizen: 'Back to citizen portal',
    signInFailed: 'Invalid credentials or not an admin account.',
    notAdmin: 'This account does not have admin/ministry privileges.',
    signupFailed: 'Admin registration failed. Check the invite code and try again.',
    signupDisabled: 'Admin registration is disabled on this deployment.',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'Language',
    dashboardTitle: 'Ministry Admin Dashboard',
    dashboardSubtitle: 'Bio-piracy radar · Citizen claims queue',
    adminBadge: 'Admin',
    patentRadar: 'Patent Radar',
    claimsQueue: 'Claims Queue',
    patentTitlePlaceholder: 'Patent title *',
    patentAbstractPlaceholder: 'Patent abstract *',
    claimsPlaceholder: 'Claims (optional)',
    runRadar: 'Run Radar Scan',
    scanning: 'Scanning…',
    risk: 'Risk',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    matchesSummary: '{total} illustrative reference matches • {high} high risk • {medium} medium risk',
    system: 'System',
    score: 'Score',
    matchedTerms: 'Matched terms',
    radarDisclaimer: 'Radar scores are heuristic TF-IDF resemblance against a small public illustrative reference set, not the official TKDL. Full source verification and legal review are required.',
    loading: 'Loading…',
    pending: 'Pending',
    verified: 'Verified',
    anchored: 'Blockchain Anchored',
    noClaims: 'No {status} claims.',
    refreshClaims: 'Refresh claims',
    verify: 'Verify',
    anchor: 'Anchor',
    requestFailed: 'The request could not be completed. Please try again.',
    unauthorized: 'Your session has expired. Sign in again.',
    adminRequired: 'Admin access is required for this action.',
    tooManyRequests: 'Too many requests. Please wait and try again.',
    claimsLoadFailed: 'Could not load claims. Please try again.',
    dynamicTranslationNotice: 'Radar finding text is shown in its original language. Enable external processing consent to translate it.',
    inputTranslationNotice: 'Non-English patent text is matched as entered. Enable external processing consent to translate it to English for better reference matching.',
    inputTranslationFailed: 'The patent text could not be translated, so the radar scan was not run.',
    translationConsent: 'I agree to send patent text to the configured external translation provider for translation.',
    translationUnavailable: 'Radar finding text could not be translated; the original text is shown.',
  },
  te: {
    ministryPortal: 'మంత్రిత్వ శాఖ / నిర్వాహక పోర్టల్',
    accessTitle: 'మంత్రిత్వ శాఖ / నియంత్రణ నిర్వాహక ప్రవేశం',
    signIn: 'సైన్ ఇన్',
    registerAdmin: 'నిర్వాహకుడిగా నమోదు',
    fullName: 'పూర్తి పేరు',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    inviteCode: 'నిర్వాహక ఆహ్వాన కోడ్',
    namePlaceholder: 'మంత్రిత్వ శాఖ అధికారి పేరు',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'మంత్రిత్వ శాఖ IT అందించినది',
    signInAsAdmin: 'నిర్వాహకుడిగా సైన్ ఇన్',
    registerAdminAccount: 'నిర్వాహక ఖాతాను నమోదు చేయండి',
    pleaseWait: 'దయచేసి వేచి ఉండండి…',
    backToCitizen: 'పౌర పోర్టల్‌కు తిరిగి వెళ్లండి',
    signInFailed: 'ప్రవేశ వివరాలు తప్పు లేదా ఈ ఖాతాకు నిర్వాహక హక్కులు లేవు.',
    notAdmin: 'ఈ ఖాతాకు మంత్రిత్వ శాఖ / నిర్వాహక హక్కులు లేవు.',
    signupFailed: 'నిర్వాహక నమోదు విఫలమైంది. ఆహ్వాన కోడ్‌ను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    signupDisabled: 'ఈ అమరికలో నిర్వాహక నమోదు నిలిపివేయబడింది.',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'భాష',
    dashboardTitle: 'మంత్రిత్వ శాఖ నిర్వాహక డాష్‌బోర్డ్',
    dashboardSubtitle: 'జీవ వైవిధ్య దోపిడీ రాడార్ · పౌరుల క్లెయిమ్‌ల క్యూ',
    adminBadge: 'నిర్వాహకుడు',
    patentRadar: 'పేటెంట్ రాడార్',
    claimsQueue: 'క్లెయిమ్‌ల క్యూ',
    patentTitlePlaceholder: 'పేటెంట్ శీర్షిక *',
    patentAbstractPlaceholder: 'పేటెంట్ సారాంశం *',
    claimsPlaceholder: 'క్లెయిమ్‌లు (ఐచ్ఛికం)',
    runRadar: 'రాడార్ స్కాన్ ప్రారంభించండి',
    scanning: 'స్కాన్ చేస్తోంది…',
    risk: 'ప్రమాదం',
    critical: 'తీవ్రమైన',
    high: 'అధిక',
    medium: 'మధ్యస్థ',
    low: 'తక్కువ',
    matchesSummary: '{total} ఉదాహరణ సూచన సరిపోలికలు • {high} అధిక ప్రమాదం • {medium} మధ్యస్థ ప్రమాదం',
    system: 'వ్యవస్థ',
    score: 'స్కోరు',
    matchedTerms: 'సరిపోలిన పదాలు',
    radarDisclaimer: 'రాడార్ స్కోర్లు చిన్న, బహిరంగ ఉదాహరణ సూచన సమూహంతో TF-IDF ఆధారిత సారూప్యతలు మాత్రమే; ఇవి అధికారిక TKDL ఫలితాలు కావు. మూలాలను ధృవీకరించి న్యాయ సమీక్ష చేయాలి.',
    loading: 'లోడ్ అవుతోంది…',
    pending: 'పెండింగ్',
    verified: 'ధృవీకరించబడింది',
    anchored: 'బ్లాక్‌చెయిన్‌లో నమోదు చేయబడింది',
    noClaims: '{status} క్లెయిమ్‌లు లేవు.',
    refreshClaims: 'క్లెయిమ్‌లను రిఫ్రెష్ చేయండి',
    verify: 'ధృవీకరించండి',
    anchor: 'బ్లాక్‌చెయిన్‌లో నమోదు చేయండి',
    requestFailed: 'అభ్యర్థన పూర్తి కాలేదు. మళ్లీ ప్రయత్నించండి.',
    unauthorized: 'మీ సెషన్ గడువు ముగిసింది. మళ్లీ సైన్ ఇన్ చేయండి.',
    adminRequired: 'ఈ చర్యకు నిర్వాహక ప్రవేశం అవసరం.',
    tooManyRequests: 'చాలా ఎక్కువ అభ్యర్థనలు వచ్చాయి. కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.',
    claimsLoadFailed: 'క్లెయిమ్‌లను లోడ్ చేయలేకపోయాము. మళ్లీ ప్రయత్నించండి.',
    dynamicTranslationNotice: 'రాడార్ ఫలితాలు వాటి అసలు భాషలో చూపబడుతున్నాయి. అనువదించడానికి బాహ్య ప్రాసెసింగ్ సమ్మతిని ప్రారంభించండి.',
    inputTranslationNotice: 'ఆంగ్లేతర పేటెంట్ పాఠ్యం ఉన్న భాషలోనే సరిపోల్చబడుతుంది. మెరుగైన సూచన సరిపోలికల కోసం ఆంగ్లంలోకి అనువదించేందుకు బాహ్య ప్రాసెసింగ్ సమ్మతిని ప్రారంభించండి.',
    inputTranslationFailed: 'పేటెంట్ పాఠ్యాన్ని అనువదించలేకపోయాము; అందువల్ల రాడార్ స్కాన్ ప్రారంభించలేదు.',
    translationConsent: 'పేటెంట్ పాఠ్యాన్ని అనువదించడానికి కాన్ఫిగర్ చేసిన బాహ్య అనువాద సేవకు పంపేందుకు నేను సమ్మతిస్తున్నాను.',
    translationUnavailable: 'రాడార్ ఫలితాలను అనువదించలేకపోయాము; అసలు పాఠ్యం చూపబడుతోంది.',
  },
  hi: {
    ministryPortal: 'मंत्रालय / व्यवस्थापक पोर्टल',
    accessTitle: 'मंत्रालय / नियामक व्यवस्थापक प्रवेश',
    signIn: 'साइन इन',
    registerAdmin: 'व्यवस्थापक पंजीकरण',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    inviteCode: 'व्यवस्थापक आमंत्रण कोड',
    namePlaceholder: 'मंत्रालय अधिकारी का नाम',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'मंत्रालय IT द्वारा दिया गया',
    signInAsAdmin: 'व्यवस्थापक के रूप में साइन इन करें',
    registerAdminAccount: 'व्यवस्थापक खाता पंजीकृत करें',
    pleaseWait: 'कृपया प्रतीक्षा करें…',
    backToCitizen: 'नागरिक पोर्टल पर वापस जाएँ',
    signInFailed: 'लॉगिन विवरण अमान्य हैं या इस खाते के पास व्यवस्थापक अधिकार नहीं हैं।',
    notAdmin: 'इस खाते के पास मंत्रालय / व्यवस्थापक अधिकार नहीं हैं।',
    signupFailed: 'व्यवस्थापक पंजीकरण विफल हुआ। आमंत्रण कोड जाँचकर फिर प्रयास करें।',
    signupDisabled: 'इस परिनियोजन में व्यवस्थापक पंजीकरण बंद है।',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'भाषा',
    dashboardTitle: 'मंत्रालय व्यवस्थापक डैशबोर्ड',
    dashboardSubtitle: 'जैव-चोरी रडार · नागरिक दावों की कतार',
    adminBadge: 'व्यवस्थापक',
    patentRadar: 'पेटेंट रडार',
    claimsQueue: 'दावा कतार',
    patentTitlePlaceholder: 'पेटेंट शीर्षक *',
    patentAbstractPlaceholder: 'पेटेंट सार *',
    claimsPlaceholder: 'दावे (वैकल्पिक)',
    runRadar: 'रडार स्कैन चलाएँ',
    scanning: 'स्कैन हो रहा है…',
    risk: 'जोखिम',
    critical: 'गंभीर',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    matchesSummary: '{total} उदाहरण संदर्भ मेल • {high} उच्च जोखिम • {medium} मध्यम जोखिम',
    system: 'प्रणाली',
    score: 'स्कोर',
    matchedTerms: 'मेल खाते शब्द',
    radarDisclaimer: 'रडार स्कोर छोटे सार्वजनिक उदाहरण-संदर्भ समूह से TF-IDF समानता पर आधारित हैं; यह आधिकारिक TKDL परिणाम नहीं है। स्रोत सत्यापन और कानूनी समीक्षा आवश्यक है।',
    loading: 'लोड हो रहा है…',
    pending: 'लंबित',
    verified: 'सत्यापित',
    anchored: 'ब्लॉकचेन पर दर्ज',
    noClaims: 'कोई {status} दावा नहीं।',
    refreshClaims: 'दावों को रीफ़्रेश करें',
    verify: 'सत्यापित करें',
    anchor: 'ब्लॉकचेन पर दर्ज करें',
    requestFailed: 'अनुरोध पूरा नहीं हो सका। कृपया फिर प्रयास करें।',
    unauthorized: 'आपका सत्र समाप्त हो गया है। फिर से साइन इन करें।',
    adminRequired: 'इस कार्रवाई के लिए व्यवस्थापक पहुँच आवश्यक है।',
    tooManyRequests: 'बहुत अधिक अनुरोध। थोड़ी देर बाद फिर प्रयास करें।',
    claimsLoadFailed: 'दावे लोड नहीं हो सके। कृपया फिर प्रयास करें।',
    dynamicTranslationNotice: 'रडार निष्कर्ष मूल भाषा में दिखाए जा रहे हैं। अनुवाद के लिए बाहरी प्रसंस्करण की सहमति सक्षम करें।',
    inputTranslationNotice: 'गैर-अंग्रेज़ी पेटेंट पाठ का मिलान उसी भाषा में होगा। बेहतर संदर्भ-मिलान के लिए अंग्रेज़ी में अनुवाद करने हेतु बाहरी प्रसंस्करण की सहमति सक्षम करें।',
    inputTranslationFailed: 'पेटेंट पाठ का अनुवाद नहीं हो सका, इसलिए रडार स्कैन नहीं चलाया गया।',
    translationConsent: 'मैं पेटेंट पाठ के अनुवाद के लिए उसे कॉन्फ़िगर की गई बाहरी अनुवाद सेवा को भेजने की सहमति देता/देती हूँ।',
    translationUnavailable: 'रडार निष्कर्षों का अनुवाद नहीं हो सका; मूल पाठ दिखाया गया है।',
  },
  ta: {
    ministryPortal: 'அமைச்சகம் / நிர்வாகி தளம்',
    accessTitle: 'அமைச்சகம் / ஒழுங்குமுறை நிர்வாகி அணுகல்',
    signIn: 'உள்நுழை',
    registerAdmin: 'நிர்வாகியாக பதிவு செய்க',
    fullName: 'முழுப் பெயர்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    inviteCode: 'நிர்வாகி அழைப்புக் குறியீடு',
    namePlaceholder: 'அமைச்சக அதிகாரியின் பெயர்',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'அமைச்சக IT வழங்கியது',
    signInAsAdmin: 'நிர்வாகியாக உள்நுழை',
    registerAdminAccount: 'நிர்வாகி கணக்கைப் பதிவு செய்க',
    pleaseWait: 'தயவுசெய்து காத்திருக்கவும்…',
    backToCitizen: 'குடிமக்கள் தளத்திற்குத் திரும்பு',
    signInFailed: 'சான்றுகள் தவறானவை அல்லது இந்தக் கணக்கிற்கு நிர்வாகி உரிமை இல்லை.',
    notAdmin: 'இந்தக் கணக்கிற்கு அமைச்சக / நிர்வாகி உரிமைகள் இல்லை.',
    signupFailed: 'நிர்வாகி பதிவு தோல்வியடைந்தது. அழைப்புக் குறியீட்டைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    signupDisabled: 'இந்தப் பயன்பாட்டில் நிர்வாகி பதிவு முடக்கப்பட்டுள்ளது.',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'மொழி',
    dashboardTitle: 'அமைச்சக நிர்வாகி டாஷ்போர்டு',
    dashboardSubtitle: 'உயிரியல் கொள்ளை ரேடார் · குடிமக்கள் கோரிக்கை வரிசை',
    adminBadge: 'நிர்வாகி',
    patentRadar: 'காப்புரிமை ரேடார்',
    claimsQueue: 'கோரிக்கை வரிசை',
    patentTitlePlaceholder: 'காப்புரிமை தலைப்பு *',
    patentAbstractPlaceholder: 'காப்புரிமை சுருக்கம் *',
    claimsPlaceholder: 'கோரிக்கைகள் (விருப்பமானவை)',
    runRadar: 'ரேடார் ஸ்கேன் இயக்கவும்',
    scanning: 'ஸ்கேன் செய்கிறது…',
    risk: 'ஆபத்து',
    critical: 'மிகவும் தீவிரம்',
    high: 'அதிகம்',
    medium: 'நடுத்தரம்',
    low: 'குறைவு',
    matchesSummary: '{total} எடுத்துக்காட்டு குறிப்பு பொருத்தங்கள் • {high} அதிக ஆபத்து • {medium} நடுத்தர ஆபத்து',
    system: 'அமைப்பு',
    score: 'மதிப்பெண்',
    matchedTerms: 'பொருந்திய சொற்கள்',
    radarDisclaimer: 'ரேடார் மதிப்பெண்கள் சிறிய பொது எடுத்துக்காட்டு குறிப்புத் தொகுப்புடன் TF-IDF ஒற்றுமையை மட்டுமே காட்டும்; இது அதிகாரப்பூர்வ TKDL முடிவு அல்ல. மூலச் சரிபார்ப்பும் சட்ட மதிப்பாய்வும் அவசியம்.',
    loading: 'ஏற்றுகிறது…',
    pending: 'நிலுவையில்',
    verified: 'சரிபார்க்கப்பட்டது',
    anchored: 'பிளாக்செயினில் பதிவு செய்யப்பட்டது',
    noClaims: '{status} கோரிக்கைகள் இல்லை.',
    refreshClaims: 'கோரிக்கைகளைப் புதுப்பிக்கவும்',
    verify: 'சரிபார்க்கவும்',
    anchor: 'பிளாக்செயினில் பதிவு செய்யவும்',
    requestFailed: 'கோரிக்கையை நிறைவேற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    unauthorized: 'உங்கள் அமர்வு காலாவதியானது. மீண்டும் உள்நுழையவும்.',
    adminRequired: 'இந்தச் செயலுக்கு நிர்வாகி அணுகல் தேவை.',
    tooManyRequests: 'அதிகமான கோரிக்கைகள். சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
    claimsLoadFailed: 'கோரிக்கைகளை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    dynamicTranslationNotice: 'ரேடார் கண்டறிதல் உரை அதன் அசல் மொழியில் காட்டப்படுகிறது. மொழிபெயர்க்க வெளிப்புற செயலாக்க ஒப்புதலை இயக்கவும்.',
    inputTranslationNotice: 'ஆங்கிலமல்லாத காப்புரிமை உரை உள்ளிடப்பட்ட மொழியிலேயே பொருத்தப்படும். சிறந்த குறிப்பு பொருத்தத்திற்கு ஆங்கிலமாக மொழிபெயர்க்க வெளிப்புற செயலாக்க ஒப்புதலை இயக்கவும்.',
    inputTranslationFailed: 'காப்புரிமை உரையை மொழிபெயர்க்க முடியவில்லை; எனவே ரேடார் ஸ்கேன் இயக்கப்படவில்லை.',
    translationConsent: 'காப்புரிமை உரையை மொழிபெயர்க்க உள்ளமைக்கப்பட்ட வெளிப்புற மொழிபெயர்ப்பு சேவைக்கு அனுப்ப ஒப்புக்கொள்கிறேன்.',
    translationUnavailable: 'ரேடார் கண்டறிதலை மொழிபெயர்க்க முடியவில்லை; அசல் உரை காட்டப்படுகிறது.',
  },
  ml: {
    ministryPortal: 'മന്ത്രാലയം / അഡ്മിൻ പോർട്ടൽ',
    accessTitle: 'മന്ത്രാലയം / നിയന്ത്രണ അഡ്മിൻ പ്രവേശനം',
    signIn: 'സൈൻ ഇൻ',
    registerAdmin: 'അഡ്മിനായി രജിസ്റ്റർ ചെയ്യുക',
    fullName: 'പൂർണ്ണ പേര്',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    inviteCode: 'അഡ്മിൻ ക്ഷണ കോഡ്',
    namePlaceholder: 'മന്ത്രാലയ ഉദ്യോഗസ്ഥന്റെ പേര്',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'മന്ത്രാലയ IT നൽകിയിരിക്കുന്നത്',
    signInAsAdmin: 'അഡ്മിനായി സൈൻ ഇൻ ചെയ്യുക',
    registerAdminAccount: 'അഡ്മിൻ അക്കൗണ്ട് രജിസ്റ്റർ ചെയ്യുക',
    pleaseWait: 'ദയവായി കാത്തിരിക്കുക…',
    backToCitizen: 'പൗര പോർട്ടലിലേക്ക് മടങ്ങുക',
    signInFailed: 'ലോഗിൻ വിവരങ്ങൾ തെറ്റാണ് അല്ലെങ്കിൽ ഈ അക്കൗണ്ടിന് അഡ്മിൻ അധികാരമില്ല.',
    notAdmin: 'ഈ അക്കൗണ്ടിന് മന്ത്രാലയ / അഡ്മിൻ അധികാരങ്ങളില്ല.',
    signupFailed: 'അഡ്മിൻ രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു. ക്ഷണ കോഡ് പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
    signupDisabled: 'ഈ വിന്യാസത്തിൽ അഡ്മിൻ രജിസ്ട്രേഷൻ പ്രവർത്തനരഹിതമാണ്.',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'ഭാഷ',
    dashboardTitle: 'മന്ത്രാലയ അഡ്മിൻ ഡാഷ്ബോർഡ്',
    dashboardSubtitle: 'ജൈവമോഷണ റഡാർ · പൗര അവകാശവാദങ്ങളുടെ നിര',
    adminBadge: 'അഡ്മിൻ',
    patentRadar: 'പേറ്റന്റ് റഡാർ',
    claimsQueue: 'അവകാശവാദങ്ങളുടെ നിര',
    patentTitlePlaceholder: 'പേറ്റന്റ് ശീർഷകം *',
    patentAbstractPlaceholder: 'പേറ്റന്റ് സംഗ്രഹം *',
    claimsPlaceholder: 'ക്ലെയിമുകൾ (ഐച്ഛികം)',
    runRadar: 'റഡാർ സ്കാൻ നടത്തുക',
    scanning: 'സ്കാൻ ചെയ്യുന്നു…',
    risk: 'അപകടസാധ്യത',
    critical: 'ഗുരുതരം',
    high: 'ഉയർന്നത്',
    medium: 'മിതമായത്',
    low: 'കുറഞ്ഞത്',
    matchesSummary: '{total} ഉദാഹരണ റഫറൻസ് പൊരുത്തങ്ങൾ • {high} ഉയർന്ന അപകടസാധ്യത • {medium} മിതമായ അപകടസാധ്യത',
    system: 'സിസ്റ്റം',
    score: 'സ്കോർ',
    matchedTerms: 'പൊരുത്തപ്പെട്ട പദങ്ങൾ',
    radarDisclaimer: 'ചെറിയ പൊതുവായ ഉദാഹരണ റഫറൻസ് സെറ്റുമായുള്ള TF-IDF സാമ്യമാണ് റഡാർ സ്കോറുകൾ; ഇത് ഔദ്യോഗിക TKDL ഫലമല്ല. ഉറവിട പരിശോധനയും നിയമ അവലോകനവും ആവശ്യമാണ്.',
    loading: 'ലോഡ് ചെയ്യുന്നു…',
    pending: 'തീർപ്പുകൽപ്പിക്കാത്തത്',
    verified: 'സ്ഥിരീകരിച്ചു',
    anchored: 'ബ്ലോക്ക്ചെയിനിൽ രേഖപ്പെടുത്തി',
    noClaims: '{status} അവകാശവാദങ്ങളില്ല.',
    refreshClaims: 'അവകാശവാദങ്ങൾ പുതുക്കുക',
    verify: 'സ്ഥിരീകരിക്കുക',
    anchor: 'ബ്ലോക്ക്ചെയിനിൽ രേഖപ്പെടുത്തുക',
    requestFailed: 'അഭ്യർത്ഥന പൂർത്തിയാക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
    unauthorized: 'നിങ്ങളുടെ സെഷൻ കാലഹരണപ്പെട്ടു. വീണ്ടും സൈൻ ഇൻ ചെയ്യുക.',
    adminRequired: 'ഈ പ്രവർത്തനത്തിന് അഡ്മിൻ പ്രവേശനം ആവശ്യമാണ്.',
    tooManyRequests: 'വളരെയധികം അഭ്യർത്ഥനകൾ. കുറച്ച് കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക.',
    claimsLoadFailed: 'അവകാശവാദങ്ങൾ ലോഡ് ചെയ്യാനായില്ല. വീണ്ടും ശ്രമിക്കുക.',
    dynamicTranslationNotice: 'റഡാർ കണ്ടെത്തലുകൾ യഥാർത്ഥ ഭാഷയിൽ കാണിക്കുന്നു. വിവർത്തനത്തിന് ബാഹ്യ പ്രോസസ്സിംഗ് സമ്മതം പ്രവർത്തനക്ഷമമാക്കുക.',
    inputTranslationNotice: 'ഇംഗ്ലീഷ് അല്ലാത്ത പേറ്റന്റ് വാചകം നൽകിയ ഭാഷയിൽ തന്നെയാണ് പൊരുത്തപ്പെടുത്തുക. മികച്ച റഫറൻസ് പൊരുത്തത്തിന് ഇംഗ്ലീഷിലേക്ക് വിവർത്തനം ചെയ്യാൻ ബാഹ്യ പ്രോസസ്സിംഗ് സമ്മതം പ്രവർത്തനക്ഷമമാക്കുക.',
    inputTranslationFailed: 'പേറ്റന്റ് വാചകം വിവർത്തനം ചെയ്യാനായില്ല; അതിനാൽ റഡാർ സ്കാൻ നടത്തിയില്ല.',
    translationConsent: 'പേറ്റന്റ് വാചകം വിവർത്തനത്തിനായി ക്രമീകരിച്ച ബാഹ്യ വിവർത്തന സേവനത്തിലേക്ക് അയയ്ക്കാൻ ഞാൻ സമ്മതിക്കുന്നു.',
    translationUnavailable: 'റഡാർ കണ്ടെത്തലുകൾ വിവർത്തനം ചെയ്യാനായില്ല; യഥാർത്ഥ വാചകം കാണിക്കുന്നു.',
  },
  sa: {
    ministryPortal: 'मन्त्रालयः / प्रशासक-पोर्टलम्',
    accessTitle: 'मन्त्रालयस्य / नियामक-प्रशासक-प्रवेशः',
    signIn: 'प्रविशन्तु',
    registerAdmin: 'प्रशासक-रूपेण पञ्जीकरणम्',
    fullName: 'पूर्णं नाम',
    email: 'ईमेल',
    password: 'गुप्तशब्दः',
    inviteCode: 'प्रशासक-निमन्त्रण-सङ्केतः',
    namePlaceholder: 'मन्त्रालय-अधिकारिणः नाम',
    emailPlaceholder: 'admin@ministry.gov.in',
    invitePlaceholder: 'मन्त्रालयस्य IT-विभागेन प्रदत्तः',
    signInAsAdmin: 'प्रशासक-रूपेण प्रविशन्तु',
    registerAdminAccount: 'प्रशासक-खातं पञ्जीकुर्वन्तु',
    pleaseWait: 'कृपया प्रतीक्षध्वम्…',
    backToCitizen: 'नागरिक-पोर्टलं प्रति निवर्तन्ताम्',
    signInFailed: 'प्रवेश-विवरणानि असत्यानि, अथवा अस्य खातस्य प्रशासकाधिकारः नास्ति।',
    notAdmin: 'अस्य खातस्य मन्त्रालय-प्रशासकाधिकाराः न सन्ति।',
    signupFailed: 'प्रशासक-पञ्जीकरणं विफलम्। निमन्त्रण-सङ्केतं परीक्ष्य पुनः प्रयतध्वम्।',
    signupDisabled: 'अस्मिन् परिनियोजने प्रशासक-पञ्जीकरणं निष्क्रियम्।',
    languageEnglish: 'English',
    languageTelugu: 'తెలుగు',
    languageHindi: 'हिन्दी',
    languageTamil: 'தமிழ்',
    languageMalayalam: 'മലയാളം',
    languageSanskrit: 'संस्कृतम्',
    languageLabel: 'भाषा',
    dashboardTitle: 'मन्त्रालय-प्रशासक-फलकम्',
    dashboardSubtitle: 'जैव-लुण्ठन-रडारः · नागरिक-दावा-पङ्क्तिः',
    adminBadge: 'प्रशासकः',
    patentRadar: 'पेटेण्ट्-रडारः',
    claimsQueue: 'दावा-पङ्क्तिः',
    patentTitlePlaceholder: 'पेटेण्ट्-शीर्षकम् *',
    patentAbstractPlaceholder: 'पेटेण्ट्-सारः *',
    claimsPlaceholder: 'दावाः (वैकल्पिकाः)',
    runRadar: 'रडार्-परीक्षणं चालयन्तु',
    scanning: 'परीक्षणं क्रियते…',
    risk: 'जोखिमम्',
    critical: 'गम्भीरम्',
    high: 'उच्चम्',
    medium: 'मध्यमम्',
    low: 'अल्पम्',
    matchesSummary: '{total} उदाहरण-सन्दर्भ-साम्यानि • {high} उच्च-जोखिमम् • {medium} मध्यम-जोखिमम्',
    system: 'प्रणाली',
    score: 'अङ्कः',
    matchedTerms: 'समान-पदानि',
    radarDisclaimer: 'रडार्-अङ्काः लघु-सार्वजनिक-उदाहरण-सन्दर्भ-समूहे TF-IDF-साम्यं दर्शयन्ति; एतत् आधिकारिकं TKDL-फलम् नास्ति। स्रोतः प्रमाणयित्वा विधि-समीक्षा आवश्यकी।',
    loading: 'आनीयते…',
    pending: 'प्रतीक्ष्यमाणम्',
    verified: 'प्रमाणितम्',
    anchored: 'ब्लॉकचेन-मध्ये अङ्कितम्',
    noClaims: 'किमपि {status} दावा नास्ति।',
    refreshClaims: 'दावान् पुनरानीयताम्',
    verify: 'प्रमाणयन्तु',
    anchor: 'ब्लॉकचेन-मध्ये अङ्कयन्तु',
    requestFailed: 'अनुरोधः सम्पन्नः नाभवत्। पुनः प्रयतध्वम्।',
    unauthorized: 'भवतः सत्रस्य अवधि समाप्ता। पुनः प्रविशन्तु।',
    adminRequired: 'अस्य कार्यस्य कृते प्रशासक-प्रवेशः आवश्यकः।',
    tooManyRequests: 'अत्यधिकाः अनुरोधाः। किञ्चित् कालं प्रतीक्ष्य पुनः प्रयतध्वम्।',
    claimsLoadFailed: 'दावान् आनेतुं न शक्यम्। पुनः प्रयतध्वम्।',
    dynamicTranslationNotice: 'रडार्-निष्कर्षाः मूलभाषायां दृश्यन्ते। अनुवादाय बाह्य-प्रक्रिया-अनुमतिं सक्रियं कुर्वन्तु।',
    inputTranslationNotice: 'अङ्ग्लभिन्नं पेटेण्ट्-पाठं स्वभाषायामेव मेलयिष्यते। उत्तम-सन्दर्भ-साम्याय आङ्ग्लभाषायाम् अनुवादार्थं बाह्य-प्रक्रिया-अनुमतिं सक्रियं कुर्वन्तु।',
    inputTranslationFailed: 'पेटेण्ट्-पाठस्य अनुवादः नाभवत्, अतः रडार्-परीक्षणं न चालितम्।',
    translationConsent: 'पेटेण्ट्-पाठस्य अनुवादाय तं विन्यस्ताय बाह्य-अनुवाद-सेवायै प्रेषयितुं अनुमन्ये।',
    translationUnavailable: 'रडार्-निष्कर्षान् अनुवादयितुं न शक्यम्; मूलपाठः दृश्यते।',
  },
}

export function getAdminCopy(language = 'en') {
  return ADMIN_COPY[language] || ADMIN_COPY.en
}

export const ADMIN_LANGUAGES = ['en', 'te', 'hi', 'ta', 'ml', 'sa']
