// UI chrome is multilingual (English / Telugu / Hindi) to demonstrate the multilingual
// architecture end-to-end. Generated legal answers are translated live via
// the backend's translation pipeline (see backend/app/translate.py); if that
// service is unreachable, the UI shows a visible "translation unavailable"
// note rather than silently displaying the wrong language.
export const COPY = {
  en: {
    appName: 'SUTRADHARA',
    tagline: 'AI-Powered IP & Regulatory Intelligence for Ayurveda',
    team: 'Team Chaturya',
    heroLede:
      'The platform connects Ayurvedic products with applicable intellectual-property regimes, regulatory requirements, jurisdiction-specific rules, and authoritative evidence.',
    heroCta: 'Analyze an Ayurvedic Product',
    pipeline: ['Product', 'Classification', 'IP', 'Regulation', 'Evidence'],

    navAnalyze: 'Analyze',
    navAbs: 'ABS Compliance',
    navTkdl: 'TKDL Check',
    navEvidence: 'Evidence',
    navGraph: 'Knowledge Graph',
    navEval: 'Evaluation',

    inputLabel: 'Describe your Ayurvedic product or IP question',
    placeholder: 'e.g. Can I patent a classical Ayurvedic formulation already described in a traditional text?',
    micStart: 'Record a voice question', micStop: 'Stop recording', micNotSupported: 'Voice input is not supported in this browser.', micPermissionDenied: 'Microphone access was denied — check your browser permissions.', micTranscribeFailed: 'Could not reach the transcription service. You can type your question instead.', micUnavailableTooltip: 'Voice input is not configured on this deployment yet.',
    readAloudStart: 'Read answer aloud', readAloudStop: 'Stop reading', readAloudNotSupported: 'Text-to-speech is not supported in this browser.', readAloudNoAnswer: 'Run an analysis to read the answer aloud.',
    analyze: 'Analyze',
    analyzing: 'Analyzing…',
    india: 'India',
    international: 'International',
    disclaimer: 'Information, not legal advice.',
    classification: 'Product Classification',
    jurisdiction: 'Jurisdiction',
    applicableAreas: 'Applicable IP & Regulatory Areas',
    assessment: 'AI Assessment',
    sources: 'Evidence & Citations',
    confidence: 'Evidence Confidence',
    escalate: 'Escalate to IP Facilitator',
    needExpert: 'Need expert assistance?',
    detectedLanguage: 'Detected input language',
    retrievalNote: 'Retrieval normalized to',
    evidenceBoundary: 'Evidence Boundary',
    evidenceBoundaryBody: 'Insufficient authoritative evidence to provide a reliable answer.',
    whyAbstained: 'Why the system abstained',
    systemError: 'Analysis service temporarily unavailable. Please try again in a moment.',

    evidencePageTitle: 'Evidence Explorer',
    evidencePageLede: 'Where did the last answer come from? Every source below was actually retrieved from the authoritative corpus for your most recent analysis — nothing here is invented.',
    evidenceEmpty: 'Run an analysis first — retrieved sources for that query will appear here.',

    graphEmpty: 'Knowledge graph data is unavailable from the backend right now.',
    evalEmpty: 'No queries logged yet in this session.',


    absTitle: 'ABS Compliance Check',
    absLede: 'Checks whether a query is likely to trigger Access-and-Benefit-Sharing obligations under the Biological Diversity Act, CBD, and the Nagoya Protocol — and what evidence supports that.',
    absPlaceholder: 'e.g. We want to commercialize a formulation using a biological resource sourced from a specific region in India',
    absButton: 'Check ABS Compliance',
    absEmpty: 'Describe the product or sourcing scenario above to see the ABS checklist here.',
    absNotTriggered: 'No clear Access-and-Benefit-Sharing signal was found for this query. This does not rule ABS out — describe the biological resource and its provenance for a more specific check.',

    tkdlTitle: 'TKDL / Prior-Art Check',
    tkdlLede: 'Points to the Traditional Knowledge Digital Library workflow relevant to a classical formulation, and surfaces the prior-art sources the system found.',
    tkdlPlaceholder: 'e.g. Is this formulation already documented as traditional knowledge in a classical text?',
    tkdlButton: 'Check TKDL / Prior Art',
    tkdlEmpty: 'Describe the formulation above to see the Traditional Knowledge pointer and related sources here.',
    tkdlNotTriggered: 'No Traditional Knowledge pointer was generated for this query — it may not be classified as classical/generic, or no TK-related source was retrieved.',

    languageEnglish: 'English', languageTelugu: 'తెలుగు', languageHindi: 'हिन्दी', languageTamil: 'Tamil', languageMalayalam: 'Malayalam', languageSanskrit: 'Sanskrit', primaryNavigation: 'Primary navigation', loadingAnalysis: 'Loading analysis',
    analysisHelper: 'Source-grounded analysis across the selected jurisdiction', jurisdictionPrefix: 'JURISDICTION',
    clarificationCategories: ['Classical / Generic Medicine', 'Patent / Proprietary Medicine', 'New / Non-Classical Drug', 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical', 'Cosmetic'],
    paraphraseVerified: 'phrased via Groq · citations verified', translationUnavailableAnswer: 'Translation service unavailable right now — showing the English answer.',
    tkPointer: 'Traditional Knowledge / Prior-Art Pointer', absConsiderations: 'Potential ABS Considerations',
    regulatoryPathway: 'Indicative Regulatory Pathway',
    pathwayDisclaimer: 'Indicative administrative sequence only — not legal advice and not a guarantee of any outcome. Confirm current forms, fees, and timelines with the named authority.',
    tkResemblance: 'Resemblance to Known Classical Formulations',
    tkResemblanceNote: 'Textual similarity to a small reference set of well-documented classical formulations — illustrative only, not a substitute for an actual TKDL search.',
    downloadPosture: 'Download IP Posture Summary (PDF)',
    absChecklist: { biologicalResource: 'Biological resource involved', provenance: 'Source/provenance identified', framework: 'Relevant ABS framework identified', source: 'Supporting source retrieved' },
    confidenceSupport: 'How strongly the retained sources support this analysis', compositeConfidence: 'composite confidence', confidenceScale: 'confidence scale',
    confidenceFactors: { retrieval_relevance: 'Retrieval relevance', source_count_factor: 'Source count', source_authority: 'Source authority', agreement: 'Domain agreement', classification_confidence: 'Classification confidence' },
    confidenceNote: 'Composite score computed from retrieval and classification signals actually produced by this analysis — never a fabricated accuracy figure.',
    translationUnavailableMessage: 'Translation service unavailable right now — showing the English message.', evidenceBoundaryReason: 'The retained evidence set was empty or its combined confidence fell below the safe-answer threshold — so the system is declining to answer rather than guess.',
    sourceLabel: 'SOURCE', matchLabel: 'match', sourceFields: { authority: 'Authority', domain: 'Domain', type: 'Source type', version: 'Version', retrieved: 'Retrieved', precision: 'Precision' }, viewSource: 'View source',
    builtFor: 'Built for the Ministry of AYUSH & All India Institute of Ayurveda', liveEvidenceTrail: 'A live evidence trail', heroTraceTitle: 'From product to provision, with the chain visible.', heroTraceBody: 'SUTRADHARA classifies the question, routes the relevant regime, and keeps the source in view.', citationGrounded: 'Citation-grounded by design',
    heroTrace: [{ label: 'Product query', value: 'Ashwagandha extract with a novel process' }, { label: 'Classification', value: 'Phytopharmaceutical / biological resource' }, { label: 'Evidence route', value: 'Biological Diversity Act, 2002 · Section 7' }], sourceRetained: 'Source retained', confidenceHigh: 'Confidence: high',
    focusedTool: 'Focused research tool', working: 'Working…', absChecklistLabel: 'ABS checklist', tkdlPointerLabel: 'TKDL pointer', preview: 'preview',
    reviewPathway: 'Human review pathway', escalateTitle: 'Escalate to IP Facilitator', escalationDescription: 'A human facilitator will review this query along with the evidence retrieved below.', escalationRecorded: 'Escalation recorded.', escalationFollowUp: 'A facilitator will follow up using the context below.',
    escalationFields: { query: 'Query', category: 'Category', jurisdiction: 'Jurisdiction', areas: 'Areas', sources: 'Sources' }, noSources: 'none', contactEmail: 'Contact email (optional)', emailPlaceholder: 'you@example.com', escalationError: 'Could not reach the escalation service — please try again.', cancel: 'Cancel', sending: 'Sending…', submit: 'Submit',
    graphGrounding: 'How the answer is grounded',
    graphKicker: 'Live reasoning', graphTitle: 'Knowledge Graph Explorer', graphLede: 'Pick a product category and jurisdiction — the graph below is traced fresh from the actual corpus every time, not a fixed diagram.',
    graphCategoryLabel: 'Product category', graphExportIntentLabel: 'Include export-readiness branch', graphRunButton: 'Trace the graph', graphStepsTitle: 'Reasoning trace',
    working: 'Working…',
    classificationCategories: { 'Classical / Generic Medicine': 'Classical / Generic Medicine', 'Patent / Proprietary Medicine': 'Patent / Proprietary Medicine', 'New / Non-Classical Drug': 'New / Non-Classical Drug', Phytopharmaceutical: 'Phytopharmaceutical', 'Ayurveda-Aahar / Nutraceutical': 'Ayurveda-Aahar / Nutraceutical', Cosmetic: 'Cosmetic' }, areaLabels: { Patents: 'Patents', 'Geographical Indications': 'Geographical Indications', Trademarks: 'Trademarks', Copyright: 'Copyright', Designs: 'Designs', 'Trade Secrets': 'Trade Secrets', 'Plant Variety Protection': 'Plant Variety Protection', 'Traditional Knowledge': 'Traditional Knowledge', 'Access-and-Benefit-Sharing': 'Access-and-Benefit-Sharing', 'Drug regulation': 'Drug regulation', Advertising: 'Advertising', Labelling: 'Labelling', 'Food / nutraceutical regulation': 'Food / nutraceutical regulation', 'Cosmetic regulation': 'Cosmetic regulation' },
    connectorsTitle: 'Paid-Source Connectors', connectorsLede: 'Link your own paid IP-search subscription so a query can optionally draw on it — every link, use, and revocation is logged, and nothing is used without your explicit choice per query.',
    connectorLinkHeading: 'Link a subscription', connectorProviderPlaceholder: 'Provider name (e.g. PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'Your API key', connectorLinkButton: 'Link connector',
    connectorPrivacyNote: 'Your key is hashed and only its last 4 characters are ever shown again. Revoking a connector immediately blocks any further use of it — no exceptions.',
    connectorsEmpty: 'No connectors linked yet in this session.', connectorScope: 'Scope', connectorLinkedAt: 'linked', connectorSelectForTest: 'Use for a test query', connectorRevokeButton: 'Revoke',
    connectorTestHeading: 'Run one query using this connector', connectorTestPlaceholder: 'e.g. Search prior art for a turmeric-based wound-healing formulation', connectorRunTest: 'Run with connector',
    navConnectors: 'Connectors',
    eval: { observability: 'System observability', title: 'Evaluation Dashboard', chartLabel: 'Confidence history chart', chartTitle: 'Confidence over logged queries', observations: 'observations', chartEmpty: 'Confidence history will trace here after the first analysis.', queryStart: 'query 01', queryLatest: 'latest query', totalQueries: 'Total queries logged', safeAbstention: 'Safe-abstention rate', averageConfidence: 'Average confidence', answerAccuracy: 'Answer accuracy', citationCorrectness: 'Citation correctness', classificationAccuracy: 'Classification accuracy', multilingualQuality: 'Multilingual response quality', pending: 'Evaluation pending', manualReviewSet: 'Evaluation pending — requires manual review against the verified test set', manualReview: 'Evaluation pending — requires manual review', emptyTitle: 'Your evidence trail starts here.', emptyBody: 'Run an analysis to populate confidence history, citation checks, and classification review.', citationReview: 'citation review', note: 'Session figures only — for automatically computed accuracy against a labeled test set, run the live benchmark below.', sessionLede: 'Real counts from this browser session only — resets when the server restarts.',
      benchmarkKicker: 'Computed live, not cached', benchmarkTitle: 'Live Evaluation Benchmark', benchmarkLede: 'Runs a labeled test set through the app right now and reports what actually comes back — not a hand-picked demo number.', benchmarkRun: 'Run benchmark', benchmarkEmpty: 'Run the benchmark to see freshly computed accuracy and the two hard safety invariants.',
      jurisdictionInvariant: 'Jurisdiction isolation', citationInvariant: 'Citation integrity', violations: 'violations', abstentionAccuracyLabel: 'Abstention accuracy', clarificationAccuracy: 'Clarification accuracy', citationHitRate: 'Citation hit rate', benchmarkItemCount: 'Computed against {n} labeled test items in data/eval_dataset.json.' },
  },
  te: {

    appName: 'సూత్రధార',
    tagline: 'ఆయుర్వేదం కోసం AI-ఆధారిత మేధో సంపత్తి & నియంత్రణ మేధస్సు',
    team: 'టీమ్ చతుర్య',
    heroLede:
      'ఈ వేదిక ఆయుర్వేద ఉత్పత్తులను వర్తించే మేధో సంపత్తి పాలనలు, నియంత్రణ అవసరాలు, అధికార-పరిధి నిర్దిష్ట నియమాలు మరియు అధికారిక ఆధారాలతో అనుసంధానిస్తుంది.',
    heroCta: 'ఆయుర్వేద ఉత్పత్తిని విశ్లేషించండి',
    pipeline: ['ఉత్పత్తి', 'వర్గీకరణ', 'IP', 'నియంత్రణ', 'ఆధారాలు'],

    navAnalyze: 'విశ్లేషణ',
    navAbs: 'ABS అనుసరణ',
    navTkdl: 'TKDL పరిశీలన',
    navEvidence: 'ఆధారాలు',
    navGraph: 'జ్ఞాన గ్రాఫ్',
    navEval: 'మూల్యాంకనం',

    inputLabel: 'మీ ఆయుర్వేద ఉత్పత్తి లేదా IP ప్రశ్నను వివరించండి',
    placeholder: 'ఉదా. సాంప్రదాయ గ్రంథంలో వివరించిన శాస్త్రీయ ఆయుర్వేద సూత్రీకరణకు నేను పేటెంట్ పొందవచ్చా?',
    micStart: 'వాయిస్ ప్రశ్నను రికార్డ్ చేయండి', micStop: 'రికార్డింగ్ ఆపండి', micNotSupported: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ మద్దతు లేదు.', micPermissionDenied: 'మైక్రోఫోన్ యాక్సెస్ నిరాకరించబడింది — మీ బ్రౌజర్ అనుమతులను తనిఖీ చేయండి.', micTranscribeFailed: 'ట్రాన్స్‌క్రిప్షన్ సేవను చేరుకోలేకపోయాము. బదులుగా మీరు మీ ప్రశ్నను టైప్ చేయవచ్చు.', micUnavailableTooltip: 'ఈ డిప్లాయ్‌మెంట్‌లో వాయిస్ ఇన్‌పుట్ ఇంకా కాన్ఫిగర్ చేయబడలేదు.',
    readAloudStart: 'సమాధానాన్ని బిగ్గరగా చదవండి', readAloudStop: 'చదవడం ఆపండి', readAloudNotSupported: 'ఈ బ్రౌజర్‌లో టెక్స్ట్-టు-స్పీచ్ మద్దతు లేదు.', readAloudNoAnswer: 'సమాధానాన్ని వినడానికి ముందుగా విశ్లేషణ నడపండి.',
    analyze: 'విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది…',
    india: 'భారతదేశం',
    international: 'అంతర్జాతీయ',
    disclaimer: 'ఇది సమాచారం మాత్రమే, న్యాయ సలహా కాదు.',
    classification: 'ఉత్పత్తి వర్గీకరణ',
    jurisdiction: 'అధికార పరిధి',
    applicableAreas: 'వర్తించే IP & నియంత్రణ అంశాలు',
    assessment: 'AI మదింపు',
    sources: 'ఆధారాలు & ఉల్లేఖనలు',
    confidence: 'ఆధార విశ్వసనీయత',
    escalate: 'IP సదుపాయకుడికి తెలియజేయండి',
    needExpert: 'నిపుణుల సహాయం కావాలా?',
    detectedLanguage: 'గుర్తించిన ఇన్‌పుట్ భాష',
    retrievalNote: 'రిట్రీవల్ కోసం సాధారణీకరించబడింది',
    evidenceBoundary: 'ఆధార పరిమితి',
    evidenceBoundaryBody: 'నమ్మదగిన సమాధానం ఇవ్వడానికి తగినంత అధికారిక ఆధారాలు లేవు.',
    whyAbstained: 'వ్యవస్థ ఎందుకు నిరాకరించింది',
    systemError: 'విశ్లేషణ సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.',

    evidencePageTitle: 'ఆధార అన్వేషణ',
    evidencePageLede: 'చివరి సమాధానం ఎక్కడ నుండి వచ్చింది? మీ ఇటీవలి విశ్లేషణ కోసం క్రింద ఉన్న ప్రతి మూలం అధికారిక కార్పస్ నుండి నిజంగా పొందబడింది.',
    evidenceEmpty: 'ముందుగా ఒక విశ్లేషణ నడపండి — ఆ ప్రశ్న కోసం పొందిన మూలాలు ఇక్కడ కనిపిస్తాయి.',

    graphEmpty: 'ప్రస్తుతం బ్యాకెండ్ నుండి నాలెడ్జ్ గ్రాఫ్ డేటా అందుబాటులో లేదు.',
    evalEmpty: 'ఈ సెషన్‌లో ఇంకా ప్రశ్నలు నమోదు కాలేదు.',


    absTitle: 'ABS అనుసరణ పరిశీలన',
    absLede: 'జీవవైవిధ్య చట్టం, CBD మరియు నాగోయా ప్రోటోకాల్ కింద యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ బాధ్యతలను ప్రశ్న ప్రేరేపించే అవకాశం ఉందో లేదో పరిశీలిస్తుంది.',
    absPlaceholder: 'ఉదా. భారతదేశంలోని ఒక నిర్దిష్ట ప్రాంతం నుండి పొందిన జీవ వనరును ఉపయోగించి సూత్రీకరణను వాణిజ్యీకరించాలనుకుంటున్నాము',
    absButton: 'ABS అనుసరణను పరిశీలించండి',
    absEmpty: 'ABS చెక్‌లిస్ట్‌ను చూడటానికి పైన ఉత్పత్తి లేదా సోర్సింగ్ దృశ్యాన్ని వివరించండి.',
    absNotTriggered: 'ఈ ప్రశ్న కోసం స్పష్టమైన యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్ సంకేతం కనుగొనబడలేదు. ఇది ABSను పూర్తిగా తోసిపుచ్చదు — మరింత నిర్దిష్టమైన పరిశీలన కోసం జీవ వనరు మరియు దాని మూలాన్ని వివరించండి.',

    tkdlTitle: 'TKDL / ముందస్తు-కళ పరిశీలన',
    tkdlLede: 'శాస్త్రీయ సూత్రీకరణకు సంబంధించిన సాంప్రదాయ జ్ఞాన డిజిటల్ లైబ్రరీ వర్క్‌ఫ్లోను సూచిస్తుంది మరియు వ్యవస్థ కనుగొన్న ముందస్తు-కళ మూలాలను చూపిస్తుంది.',
    tkdlPlaceholder: 'ఉదా. ఈ సూత్రీకరణ ఇప్పటికే ఒక శాస్త్రీయ గ్రంథంలో సాంప్రదాయ జ్ఞానంగా నమోదు చేయబడిందా?',
    tkdlButton: 'TKDL / ముందస్తు-కళను పరిశీలించండి',
    tkdlEmpty: 'సాంప్రదాయ జ్ఞాన సూచన మరియు సంబంధిత మూలాలను చూడటానికి పైన సూత్రీకరణను వివరించండి.',
    tkdlNotTriggered: 'ఈ ప్రశ్న కోసం సాంప్రదాయ జ్ఞాన సూచన రూపొందించబడలేదు — ఇది శాస్త్రీయ/సాధారణంగా వర్గీకరించబడకపోవచ్చు, లేదా TK-సంబంధిత మూలం పొందబడలేదు.',

    languageEnglish: 'ఇంగ్లీష్', languageTelugu: 'తెలుగు', languageHindi: 'హిందీ', languageTamil: 'తమిళం', languageMalayalam: 'మలయాళం', languageSanskrit: 'సంస్కృతం', primaryNavigation: 'ప్రధాన నావిగేషన్', loadingAnalysis: 'విశ్లేషణ లోడ్ అవుతోంది',
    analysisHelper: 'ఎంచుకున్న అధికార పరిధిలో ఆధారాలతో కూడిన విశ్లేషణ', jurisdictionPrefix: 'అధికార పరిధి',
    clarificationCategories: ['శాస్త్రీయ / సాధారణ ఔషధం', 'పేటెంట్ / స్వంత ఔషధం', 'కొత్త / శాస్త్రీయేతర ఔషధం', 'ఫైటోఫార్మాస్యూటికల్', 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', 'కాస్మెటిక్'],
    paraphraseVerified: 'Groq ద్వారా రూపుదిద్దబడింది · ఉల్లేఖనలు ధృవీకరించబడ్డాయి', translationUnavailableAnswer: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సమాధానం చూపబడుతోంది.',
    tkPointer: 'సాంప్రదాయ జ్ఞానం / ముందస్తు-కళ సూచన', absConsiderations: 'సంభావ్య ABS పరిశీలనలు',
    regulatoryPathway: 'సూచనాత్మక నియంత్రణ మార్గం',
    pathwayDisclaimer: 'ఇది కేవలం సూచనాత్మక పరిపాలనా క్రమం మాత్రమే — న్యాయ సలహా కాదు, ఫలితానికి హామీ కాదు. ప్రస్తుత ఫారాలు, రుసుములు, కాలపరిమితులను సంబంధిత అధికారితో నిర్ధారించుకోండి.',
    tkResemblance: 'తెలిసిన శాస్త్రీయ సూత్రీకరణలతో సారూప్యత',
    tkResemblanceNote: 'బాగా డాక్యుమెంట్ చేయబడిన శాస్త్రీయ సూత్రీకరణల చిన్న సూచన సమితితో వచన సారూప్యత — ఇది ఉదాహరణ మాత్రమే, వాస్తవ TKDL శోధనకు ప్రత్యామ్నాయం కాదు.',
    downloadPosture: 'IP పొజిషన్ సారాంశం డౌన్‌లోడ్ చేయండి (PDF)',
    absChecklist: { biologicalResource: 'జీవ వనరు ఉంది', provenance: 'మూలం / ప్రోవెనెన్స్ గుర్తించబడింది', framework: 'సంబంధిత ABS ఫ్రేమ్‌వర్క్ గుర్తించబడింది', source: 'మద్దతు మూలం పొందబడింది' },
    confidenceSupport: 'నిలుపుకున్న మూలాలు ఈ విశ్లేషణకు ఎంత బలంగా మద్దతు ఇస్తున్నాయి', compositeConfidence: 'సమ్మిళిత విశ్వసనీయత', confidenceScale: 'విశ్వసనీయత స్థాయి',
    confidenceFactors: { retrieval_relevance: 'రిట్రీవల్ సంబంధితత', source_count_factor: 'మూలాల సంఖ్య', source_authority: 'మూల అధికారికత', agreement: 'డొమైన్ సమ్మతి', classification_confidence: 'వర్గీకరణ విశ్వసనీయత' },
    confidenceNote: 'ఈ విశ్లేషణలో నిజంగా ఉత్పత్తి అయిన రిట్రీవల్ మరియు వర్గీకరణ సంకేతాల ఆధారంగా సమ్మిళిత స్కోరు లెక్కించబడుతుంది — కల్పిత ఖచ్చితత్వం కాదు.',
    translationUnavailableMessage: 'అనువాద సేవ ప్రస్తుతం అందుబాటులో లేదు — ఇంగ్లీష్ సందేశం చూపబడుతోంది.', evidenceBoundaryReason: 'నిలుపుకున్న ఆధారాల సమితి ఖాళీగా ఉంది లేదా దాని సమ్మిళిత విశ్వసనీయత సురక్షిత సమాధాన పరిమితి కంటే తక్కువగా ఉంది — అందువల్ల వ్యవస్థ ఊహించి సమాధానం ఇవ్వడం లేదు.',
    sourceLabel: 'మూలం', matchLabel: 'సరిపోలిక', sourceFields: { authority: 'అధికారికత', domain: 'డొమైన్', type: 'మూల రకం', version: 'వెర్షన్', retrieved: 'పొందిన తేదీ', precision: 'ఖచ్చితత్వం' }, viewSource: 'మూలాన్ని చూడండి',
    builtFor: 'ఆయుష్ మంత్రిత్వ శాఖ & ఆల్ ఇండియా ఇన్‌స్టిట్యూట్ ఆఫ్ ఆయుర్వేదం కోసం నిర్మించబడింది', liveEvidenceTrail: 'ప్రత్యక్ష ఆధార మార్గం', heroTraceTitle: 'ఉత్పత్తి నుండి నిబంధన వరకు, మొత్తం మార్గం కనిపిస్తుంది.', heroTraceBody: 'SUTRADHARA ప్రశ్నను వర్గీకరిస్తుంది, సంబంధిత పాలనకు మార్గనిర్దేశం చేస్తుంది మరియు మూలాన్ని చూపిస్తుంది.', citationGrounded: 'ఉల్లేఖన ఆధారితం',
    heroTrace: [{ label: 'ఉత్పత్తి ప్రశ్న', value: 'కొత్త ప్రక్రియతో అశ్వగంధ సారం' }, { label: 'వర్గీకరణ', value: 'ఫైటోఫార్మాస్యూటికల్ / జీవ వనరు' }, { label: 'ఆధార మార్గం', value: 'జీవ వైవిధ్య చట్టం, 2002 · సెక్షన్ 7' }], sourceRetained: 'మూలం నిలుపబడింది', confidenceHigh: 'విశ్వసనీయత: అధిక',
    focusedTool: 'కేంద్రీకృత పరిశోధన సాధనం', working: 'పని జరుగుతోంది…', absChecklistLabel: 'ABS చెక్‌లిస్ట్', tkdlPointerLabel: 'TKDL సూచన', preview: 'పరిదృశ్యం',
    reviewPathway: 'మానవ సమీక్ష మార్గం', escalateTitle: 'IP సదుపాయకుడికి పంపండి', escalationDescription: 'మానవ సదుపాయకుడు ఈ ప్రశ్నను మరియు దిగువ పొందిన ఆధారాలను సమీక్షిస్తారు.', escalationRecorded: 'ఎస్కలేషన్ నమోదు చేయబడింది.', escalationFollowUp: 'దిగువ సందర్భాన్ని ఉపయోగించి సదుపాయకుడు మిమ్మల్ని సంప్రదిస్తారు.',
    escalationFields: { query: 'ప్రశ్న', category: 'వర్గం', jurisdiction: 'అధికార పరిధి', areas: 'అంశాలు', sources: 'మూలాలు' }, noSources: 'ఏవీ లేవు', contactEmail: 'సంప్రదింపు ఇమెయిల్ (ఐచ్ఛికం)', emailPlaceholder: 'you@example.com', escalationError: 'ఎస్కలేషన్ సేవను చేరుకోలేకపోయాం — మళ్లీ ప్రయత్నించండి.', cancel: 'రద్దు', sending: 'పంపుతోంది…', submit: 'సమర్పించండి',
    graphGrounding: 'సమాధానం ఎలా ఆధారపడింది',
    graphKicker: 'ప్రత్యక్ష తార్కికం', graphTitle: 'నాలెడ్జ్ గ్రాఫ్ అన్వేషణ', graphLede: 'ఉత్పత్తి వర్గం మరియు అధికార పరిధిని ఎంచుకోండి — దిగువ గ్రాఫ్ ప్రతిసారీ వాస్తవ కార్పస్ నుండి తాజాగా రూపొందించబడుతుంది.',
    graphCategoryLabel: 'ఉత్పత్తి వర్గం', graphExportIntentLabel: 'ఎగుమతి-సంసిద్ధత శాఖను చేర్చండి', graphRunButton: 'గ్రాఫ్‌ను గుర్తించండి', graphStepsTitle: 'తార్కిక పథం',
    working: 'పని జరుగుతోంది…',
    connectorsTitle: 'చెల్లింపు-మూల కనెక్టర్లు', connectorsLede: 'మీ స్వంత చెల్లింపు IP-శోధన సభ్యత్వాన్ని లింక్ చేయండి — ప్రతి లింక్, వినియోగం, రద్దు అన్నీ లాగ్ చేయబడతాయి.',
    connectorLinkHeading: 'సభ్యత్వాన్ని లింక్ చేయండి', connectorProviderPlaceholder: 'ప్రొవైడర్ పేరు (ఉదా. PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'మీ API కీ', connectorLinkButton: 'కనెక్టర్‌ను లింక్ చేయండి',
    connectorPrivacyNote: 'మీ కీ హాష్ చేయబడుతుంది; చివరి 4 అక్షరాలు మాత్రమే మళ్లీ చూపబడతాయి. రద్దు చేయడం వెంటనే తదుపరి వినియోగాన్ని నిరోధిస్తుంది.',
    connectorsEmpty: 'ఈ సెషన్‌లో ఇంకా కనెక్టర్లు లింక్ చేయబడలేదు.', connectorScope: 'పరిధి', connectorLinkedAt: 'లింక్ చేయబడింది', connectorSelectForTest: 'పరీక్ష ప్రశ్న కోసం ఉపయోగించండి', connectorRevokeButton: 'రద్దు చేయండి',
    connectorTestHeading: 'ఈ కనెక్టర్‌తో ఒక ప్రశ్నను నడపండి', connectorTestPlaceholder: 'ఉదా. పసుపు-ఆధారిత గాయం-నయం చేసే సూత్రీకరణ కోసం ముందస్తు-కళను శోధించండి', connectorRunTest: 'కనెక్టర్‌తో నడపండి',
    navConnectors: 'కనెక్టర్లు',
    classificationCategories: { 'Classical / Generic Medicine': 'శాస్త్రీయ / సాధారణ ఔషధం', 'Patent / Proprietary Medicine': 'పేటెంట్ / స్వంత ఔషధం', 'New / Non-Classical Drug': 'కొత్త / శాస్త్రీయేతర ఔషధం', Phytopharmaceutical: 'ఫైటోఫార్మాస్యూటికల్', 'Ayurveda-Aahar / Nutraceutical': 'ఆయుర్వేద-ఆహార / న్యూట్రాస్యూటికల్', Cosmetic: 'కాస్మెటిక్' }, areaLabels: { Patents: 'పేటెంట్లు', 'Geographical Indications': 'భౌగోళిక సూచనలు', Trademarks: 'ట్రేడ్‌మార్క్‌లు', Copyright: 'కాపీరైట్', Designs: 'డిజైన్లు', 'Trade Secrets': 'వాణిజ్య రహస్యాలు', 'Plant Variety Protection': 'మొక్కల రకం రక్షణ', 'Traditional Knowledge': 'సాంప్రదాయ జ్ఞానం', 'Access-and-Benefit-Sharing': 'యాక్సెస్-అండ్-బెనిఫిట్-షేరింగ్', 'Drug regulation': 'ఔషధ నియంత్రణ', Advertising: 'ప్రకటనలు', Labelling: 'లేబులింగ్', 'Food / nutraceutical regulation': 'ఆహార / న్యూట్రాస్యూటికల్ నియంత్రణ', 'Cosmetic regulation': 'కాస్మెటిక్ నియంత్రణ' },
    eval: { observability: 'వ్యవస్థ పరిశీలన', title: 'మూల్యాంకన డ్యాష్‌బోర్డ్', chartLabel: 'విశ్వసనీయత చరిత్ర చార్ట్', chartTitle: 'లాగ్ చేసిన ప్రశ్నల విశ్వసనీయత', observations: 'పరిశీలనలు', chartEmpty: 'మొదటి విశ్లేషణ తర్వాత విశ్వసనీయత చరిత్ర ఇక్కడ కనిపిస్తుంది.', queryStart: 'ప్రశ్న 01', queryLatest: 'తాజా ప్రశ్న', totalQueries: 'మొత్తం లాగ్ చేసిన ప్రశ్నలు', safeAbstention: 'సురక్షిత నిరాకరణ రేటు', averageConfidence: 'సగటు విశ్వసనీయత', answerAccuracy: 'సమాధాన ఖచ్చితత్వం', citationCorrectness: 'ఉల్లేఖన ఖచ్చితత్వం', classificationAccuracy: 'వర్గీకరణ ఖచ్చితత్వం', multilingualQuality: 'బహుభాషా సమాధాన నాణ్యత', pending: 'మూల్యాంకనం పెండింగ్‌లో ఉంది', manualReviewSet: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — ధృవీకరించిన పరీక్షా సమితితో మానవ సమీక్ష అవసరం', manualReview: 'మూల్యాంకనం పెండింగ్‌లో ఉంది — మానవ సమీక్ష అవసరం', emptyTitle: 'మీ ఆధార మార్గం ఇక్కడ ప్రారంభమవుతుంది.', emptyBody: 'విశ్వసనీయత చరిత్ర, ఉల్లేఖన తనిఖీలు మరియు వర్గీకరణ సమీక్షను నింపడానికి విశ్లేషణ నడపండి.', citationReview: 'ఉల్లేఖన సమీక్ష', note: 'సెషన్ గణాంకాలు మాత్రమే — దిగువన ఉన్న ప్రత్యక్ష బెంచ్‌మార్క్‌ను నడపండి.', sessionLede: 'ఈ బ్రౌజర్ సెషన్ నుండి మాత్రమే వాస్తవ గణనలు.',
      benchmarkKicker: 'ప్రత్యక్షంగా లెక్కించబడింది', benchmarkTitle: 'ప్రత్యక్ష మూల్యాంకన బెంచ్‌మార్క్', benchmarkLede: 'లేబుల్ చేసిన పరీక్షా సమితిని ఇప్పుడే యాప్ ద్వారా నడుపుతుంది.', benchmarkRun: 'బెంచ్‌మార్క్ నడపండి', benchmarkEmpty: 'ఖచ్చితత్వం మరియు భద్రతా నియమాలను చూడటానికి బెంచ్‌మార్క్‌ను నడపండి.',
      jurisdictionInvariant: 'అధికార పరిధి వేరుచేత', citationInvariant: 'ఉల్లేఖన సమగ్రత', violations: 'ఉల్లంఘనలు', abstentionAccuracyLabel: 'నిరాకరణ ఖచ్చితత్వం', clarificationAccuracy: 'స్పష్టీకరణ ఖచ్చితత్వం', citationHitRate: 'ఉల్లేఖన హిట్ రేటు', benchmarkItemCount: '{n} లేబుల్ చేసిన పరీక్షా అంశాలకు వ్యతిరేకంగా లెక్కించబడింది.' },
  },
  hi: {
    appName: 'सूत्रधार',
    tagline: 'आयुर्वेद के लिए AI-संचालित IP और नियामक बुद्धिमत्ता',
    team: 'टीम चातुर्य',
    heroLede: 'यह मंच आयुर्वेदिक उत्पादों को लागू बौद्धिक संपदा व्यवस्थाओं, नियामक आवश्यकताओं, क्षेत्राधिकार-विशिष्ट नियमों और आधिकारिक प्रमाणों से जोड़ता है।',
    heroCta: 'आयुर्वेदिक उत्पाद का विश्लेषण करें',
    pipeline: ['उत्पाद', 'वर्गीकरण', 'IP', 'नियामक', 'प्रमाण'],

    navAnalyze: 'विश्लेषण',
    navAbs: 'ABS अनुपालन',
    navTkdl: 'TKDL जांच',
    navEvidence: 'प्रमाण',
    navGraph: 'ज्ञान ग्राफ',
    navEval: 'मूल्यांकन',

    inputLabel: 'अपने आयुर्वेदिक उत्पाद या IP प्रश्न का वर्णन करें',
    placeholder: 'उदा. क्या पारंपरिक ग्रंथ में वर्णित शास्त्रीय आयुर्वेदिक फॉर्मूलेशन का पेटेंट लिया जा सकता है?',
    micStart: 'आवाज़ से प्रश्न रिकॉर्ड करें', micStop: 'रिकॉर्डिंग रोकें', micNotSupported: 'इस ब्राउज़र में वॉइस इनपुट समर्थित नहीं है।', micPermissionDenied: 'माइक्रोफ़ोन एक्सेस अस्वीकृत किया गया — अपनी ब्राउज़र अनुमतियाँ जाँचें।', micTranscribeFailed: 'ट्रांसक्रिप्शन सेवा तक नहीं पहुँच सके। आप इसके बजाय अपना प्रश्न टाइप कर सकते हैं।', micUnavailableTooltip: 'इस डिप्लॉयमेंट पर वॉइस इनपुट अभी कॉन्फ़िगर नहीं किया गया है।',
    readAloudStart: 'उत्तर ज़ोर से पढ़ें', readAloudStop: 'पढ़ना रोकें', readAloudNotSupported: 'इस ब्राउज़र में टेक्स्ट-टू-स्पीच समर्थित नहीं है।', readAloudNoAnswer: 'उत्तर सुनने के लिए पहले विश्लेषण चलाएँ।',
    analyze: 'विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है…',
    india: 'भारत',
    international: 'अंतरराष्ट्रीय',
    disclaimer: 'यह जानकारी है, कानूनी सलाह नहीं।',
    classification: 'उत्पाद वर्गीकरण',
    jurisdiction: 'क्षेत्राधिकार',
    applicableAreas: 'लागू IP और नियामक क्षेत्र',
    assessment: 'AI आकलन',
    sources: 'प्रमाण और उद्धरण',
    confidence: 'प्रमाण विश्वसनीयता',
    escalate: 'IP सुविधा केंद्र को भेजें',
    needExpert: 'विशेषज्ञ सहायता चाहिए?',
    detectedLanguage: 'पहचानी गई इनपुट भाषा',
    retrievalNote: 'रिट्रीवल के लिए सामान्यीकृत',
    evidenceBoundary: 'प्रमाण सीमा',
    evidenceBoundaryBody: 'विश्वसनीय उत्तर देने के लिए पर्याप्त आधिकारिक प्रमाण उपलब्ध नहीं है।',
    whyAbstained: 'प्रणाली ने उत्तर क्यों रोका',
    systemError: 'विश्लेषण सेवा अभी अस्थायी रूप से अनुपलब्ध है। कृपया कुछ देर बाद फिर प्रयास करें।',

    evidencePageTitle: 'प्रमाण अन्वेषक',
    evidencePageLede: 'पिछला उत्तर कहाँ से आया? नीचे दिया गया प्रत्येक स्रोत आपके नवीनतम विश्लेषण के लिए आधिकारिक कॉर्पस से प्राप्त किया गया है।',
    evidenceEmpty: 'पहले विश्लेषण चलाएँ — उस प्रश्न के प्राप्त स्रोत यहाँ दिखाई देंगे।',

    graphEmpty: 'इस समय बैकएंड से ज्ञान ग्राफ डेटा उपलब्ध नहीं है।',
    evalEmpty: 'इस सत्र में अभी तक कोई प्रश्न लॉग नहीं हुआ है।',

    absTitle: 'ABS अनुपालन जांच',
    absLede: 'यह जांचता है कि कोई प्रश्न जैव विविधता अधिनियम, CBD और नागोया प्रोटोकॉल के तहत Access-and-Benefit-Sharing दायित्व शुरू कर सकता है या नहीं।',
    absPlaceholder: 'उदा. हम भारत के किसी क्षेत्र से प्राप्त जैविक संसाधन का उपयोग करने वाले फॉर्मूलेशन का व्यावसायीकरण करना चाहते हैं',
    absButton: 'ABS अनुपालन जांचें',
    absEmpty: 'ABS चेकलिस्ट देखने के लिए ऊपर उत्पाद या सोर्सिंग स्थिति का वर्णन करें।',
    absNotTriggered: 'इस प्रश्न में ABS का स्पष्ट संकेत नहीं मिला। यह ABS को पूरी तरह नकारता नहीं है — अधिक विशिष्ट जांच के लिए जैविक संसाधन और उसका स्रोत बताएं।',

    tkdlTitle: 'TKDL / पूर्व कला जांच',
    tkdlLede: 'यह शास्त्रीय फॉर्मूलेशन से संबंधित Traditional Knowledge Digital Library प्रक्रिया और मिले हुए पूर्व कला स्रोत दिखाता है।',
    tkdlPlaceholder: 'उदा. क्या यह फॉर्मूलेशन पहले से किसी शास्त्रीय ग्रंथ में पारंपरिक ज्ञान के रूप में दर्ज है?',
    tkdlButton: 'TKDL / पूर्व कला जांचें',
    tkdlEmpty: 'TKDL संकेत और संबंधित स्रोत देखने के लिए ऊपर फॉर्मूलेशन का वर्णन करें।',
    tkdlNotTriggered: 'इस प्रश्न के लिए पारंपरिक ज्ञान संकेत नहीं बनाया गया — यह शास्त्रीय/सामान्य श्रेणी में नहीं आता हो सकता है या कोई संबंधित स्रोत नहीं मिला।',

    languageEnglish: 'अंग्रेज़ी', languageTelugu: 'तेलुगु', languageHindi: 'हिन्दी', languageTamil: 'तमिल', languageMalayalam: 'मलयालम', languageSanskrit: 'संस्कृत', primaryNavigation: 'मुख्य नेविगेशन', loadingAnalysis: 'विश्लेषण लोड हो रहा है',
    analysisHelper: 'चयनित क्षेत्राधिकार में प्रमाण-आधारित विश्लेषण', jurisdictionPrefix: 'क्षेत्राधिकार',
    clarificationCategories: ['शास्त्रीय / सामान्य औषधि', 'पेटेंट / स्वामित्व वाली औषधि', 'नई / गैर-शास्त्रीय औषधि', 'फाइटोफार्मास्यूटिकल', 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', 'कॉस्मेटिक'],
    paraphraseVerified: 'Groq द्वारा रूपांतरित · उद्धरण सत्यापित', translationUnavailableAnswer: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी उत्तर दिखाया जा रहा है।',
    tkPointer: 'पारंपरिक ज्ञान / पूर्व कला संकेत', absConsiderations: 'संभावित ABS विचार',
    regulatoryPathway: 'सांकेतिक नियामक मार्ग',
    pathwayDisclaimer: 'यह केवल एक सांकेतिक प्रशासनिक क्रम है — कानूनी सलाह नहीं है और किसी परिणाम की गारंटी नहीं है। मौजूदा फॉर्म, शुल्क और समय-सीमा की पुष्टि संबंधित प्राधिकरण से करें।',
    tkResemblance: 'ज्ञात शास्त्रीय फॉर्मूलेशन से समानता',
    tkResemblanceNote: 'सुदस्तावेज़ीकृत शास्त्रीय फॉर्मूलेशन के एक छोटे संदर्भ सेट से पाठ्य समानता — यह केवल उदाहरणात्मक है, वास्तविक TKDL खोज का विकल्प नहीं।',
    downloadPosture: 'IP स्थिति सारांश डाउनलोड करें (PDF)',
    absChecklist: { biologicalResource: 'जैविक संसाधन शामिल है', provenance: 'स्रोत / उत्पत्ति पहचानी गई', framework: 'संबंधित ABS ढांचा पहचाना गया', source: 'समर्थन स्रोत प्राप्त हुआ' },
    confidenceSupport: 'रखे गए स्रोत इस विश्लेषण का कितना मजबूत समर्थन करते हैं', compositeConfidence: 'समग्र विश्वसनीयता', confidenceScale: 'विश्वसनीयता पैमाना',
    confidenceFactors: { retrieval_relevance: 'रिट्रीवल प्रासंगिकता', source_count_factor: 'स्रोत संख्या', source_authority: 'स्रोत की प्रामाणिकता', agreement: 'डोमेन सहमति', classification_confidence: 'वर्गीकरण विश्वसनीयता' },
    confidenceNote: 'समग्र स्कोर इस विश्लेषण से प्राप्त रिट्रीवल और वर्गीकरण संकेतों से बनाया जाता है — यह कोई गढ़ी हुई सटीकता नहीं है।',
    translationUnavailableMessage: 'अनुवाद सेवा अभी उपलब्ध नहीं है — अंग्रेज़ी संदेश दिखाया जा रहा है।', evidenceBoundaryReason: 'रखे गए प्रमाण खाली थे या उनकी संयुक्त विश्वसनीयता सुरक्षित उत्तर सीमा से कम थी — इसलिए प्रणाली अनुमान लगाकर उत्तर देने से इनकार कर रही है।',
    sourceLabel: 'स्रोत', matchLabel: 'मिलान', sourceFields: { authority: 'प्राधिकरण', domain: 'डोमेन', type: 'स्रोत प्रकार', version: 'संस्करण', retrieved: 'प्राप्त', precision: 'सटीकता' }, viewSource: 'स्रोत देखें',
    builtFor: 'आयुष मंत्रालय और अखिल भारतीय आयुर्वेद संस्थान के लिए निर्मित', liveEvidenceTrail: 'एक जीवंत प्रमाण मार्ग', heroTraceTitle: 'उत्पाद से प्रावधान तक, पूरी श्रृंखला दिखाई देती है।', heroTraceBody: 'SUTRADHARA प्रश्न को वर्गीकृत करता है, संबंधित व्यवस्था तक पहुँचाता है और स्रोत को सामने रखता है।', citationGrounded: 'उद्धरण-आधारित प्रणाली',
    heroTrace: [{ label: 'उत्पाद प्रश्न', value: 'नई प्रक्रिया वाला अश्वगंधा अर्क' }, { label: 'वर्गीकरण', value: 'फाइटोफार्मास्यूटिकल / जैविक संसाधन' }, { label: 'प्रमाण मार्ग', value: 'जैव विविधता अधिनियम, 2002 · धारा 7' }], sourceRetained: 'स्रोत सुरक्षित', confidenceHigh: 'विश्वसनीयता: उच्च',
    focusedTool: 'केंद्रित शोध उपकरण', working: 'काम हो रहा है…', absChecklistLabel: 'ABS चेकलिस्ट', tkdlPointerLabel: 'TKDL संकेत', preview: 'पूर्वावलोकन',
    reviewPathway: 'मानव समीक्षा मार्ग', escalateTitle: 'IP सुविधा केंद्र को भेजें', escalationDescription: 'एक मानव सुविधाकर्ता नीचे प्राप्त प्रमाणों के साथ इस प्रश्न की समीक्षा करेगा।', escalationRecorded: 'एस्केलेशन दर्ज हो गया है।', escalationFollowUp: 'सुविधाकर्ता नीचे दिए गए संदर्भ के आधार पर आपसे संपर्क करेगा।',
    escalationFields: { query: 'प्रश्न', category: 'श्रेणी', jurisdiction: 'क्षेत्राधिकार', areas: 'क्षेत्र', sources: 'स्रोत' }, noSources: 'कोई नहीं', contactEmail: 'संपर्क ईमेल (वैकल्पिक)', emailPlaceholder: 'you@example.com', escalationError: 'एस्केलेशन सेवा तक नहीं पहुँच सके — कृपया फिर प्रयास करें।', cancel: 'रद्द करें', sending: 'भेजा जा रहा है…', submit: 'जमा करें',
    graphGrounding: 'उत्तर किस तरह प्रमाणित है',
    graphKicker: 'लाइव तर्क', graphTitle: 'नॉलेज ग्राफ एक्सप्लोरर', graphLede: 'उत्पाद श्रेणी और क्षेत्राधिकार चुनें — नीचे दिया गया ग्राफ हर बार वास्तविक कॉर्पस से ताज़ा बनाया जाता है, यह कोई निश्चित आरेख नहीं है।',
    graphCategoryLabel: 'उत्पाद श्रेणी', graphExportIntentLabel: 'निर्यात-तत्परता शाखा शामिल करें', graphRunButton: 'ग्राफ ट्रेस करें', graphStepsTitle: 'तर्क पथ',
    working: 'कार्य हो रहा है…',
    connectorsTitle: 'सशुल्क-स्रोत कनेक्टर', connectorsLede: 'अपनी खुद की सशुल्क IP-खोज सदस्यता लिंक करें — हर लिंक, उपयोग और निरस्तीकरण लॉग किया जाता है।',
    connectorLinkHeading: 'सदस्यता लिंक करें', connectorProviderPlaceholder: 'प्रदाता नाम (जैसे PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'आपकी API कुंजी', connectorLinkButton: 'कनेक्टर लिंक करें',
    connectorPrivacyNote: 'आपकी कुंजी हैश की जाती है; केवल अंतिम 4 अक्षर फिर से दिखाए जाते हैं। निरस्त करने पर तुरंत आगे का उपयोग अवरुद्ध हो जाता है।',
    connectorsEmpty: 'इस सत्र में अभी तक कोई कनेक्टर लिंक नहीं किया गया।', connectorScope: 'दायरा', connectorLinkedAt: 'लिंक किया गया', connectorSelectForTest: 'परीक्षण प्रश्न के लिए उपयोग करें', connectorRevokeButton: 'निरस्त करें',
    connectorTestHeading: 'इस कनेक्टर के साथ एक प्रश्न चलाएँ', connectorTestPlaceholder: 'जैसे हल्दी-आधारित घाव भरने के फॉर्मूलेशन के लिए पूर्व कला खोजें', connectorRunTest: 'कनेक्टर के साथ चलाएँ',
    navConnectors: 'कनेक्टर',
    classificationCategories: { 'Classical / Generic Medicine': 'शास्त्रीय / सामान्य औषधि', 'Patent / Proprietary Medicine': 'पेटेंट / स्वामित्व वाली औषधि', 'New / Non-Classical Drug': 'नई / गैर-शास्त्रीय औषधि', Phytopharmaceutical: 'फाइटोफार्मास्यूटिकल', 'Ayurveda-Aahar / Nutraceutical': 'आयुर्वेद-आहार / न्यूट्रास्यूटिकल', Cosmetic: 'कॉस्मेटिक' }, areaLabels: { Patents: 'पेटेंट', 'Geographical Indications': 'भौगोलिक संकेत', Trademarks: 'ट्रेडमार्क', Copyright: 'कॉपीराइट', Designs: 'डिज़ाइन', 'Trade Secrets': 'व्यापार रहस्य', 'Plant Variety Protection': 'पादप किस्म संरक्षण', 'Traditional Knowledge': 'पारंपरिक ज्ञान', 'Access-and-Benefit-Sharing': 'लाभ-साझाकरण', 'Drug regulation': 'औषधि नियमन', Advertising: 'विज्ञापन', Labelling: 'लेबलिंग', 'Food / nutraceutical regulation': 'खाद्य / न्यूट्रास्यूटिकल नियमन', 'Cosmetic regulation': 'कॉस्मेटिक नियमन' },
    eval: { observability: 'प्रणाली अवलोकन', title: 'मूल्यांकन डैशबोर्ड', chartLabel: 'विश्वसनीयता इतिहास चार्ट', chartTitle: 'लॉग किए गए प्रश्नों की विश्वसनीयता', observations: 'अवलोकन', chartEmpty: 'पहले विश्लेषण के बाद विश्वसनीयता इतिहास यहाँ दिखाई देगा।', queryStart: 'प्रश्न 01', queryLatest: 'नवीनतम प्रश्न', totalQueries: 'लॉग किए गए कुल प्रश्न', safeAbstention: 'सुरक्षित उत्तर-त्याग दर', averageConfidence: 'औसत विश्वसनीयता', answerAccuracy: 'उत्तर सटीकता', citationCorrectness: 'उद्धरण शुद्धता', classificationAccuracy: 'वर्गीकरण सटीकता', multilingualQuality: 'बहुभाषी उत्तर गुणवत्ता', pending: 'मूल्यांकन लंबित है', manualReviewSet: 'मूल्यांकन लंबित है — सत्यापित परीक्षण सेट के साथ मानव समीक्षा आवश्यक है', manualReview: 'मूल्यांकन लंबित है — मानव समीक्षा आवश्यक है', emptyTitle: 'आपका प्रमाण मार्ग यहाँ से शुरू होता है।', emptyBody: 'विश्वसनीयता इतिहास, उद्धरण जांच और वर्गीकरण समीक्षा भरने के लिए विश्लेषण चलाएँ।', citationReview: 'उद्धरण समीक्षा', note: 'केवल सत्र आँकड़े — नीचे दिया गया लाइव बेंचमार्क चलाएँ।', sessionLede: 'केवल इस ब्राउज़र सत्र से वास्तविक गणना।',
      benchmarkKicker: 'लाइव गणना, कैश्ड नहीं', benchmarkTitle: 'लाइव मूल्यांकन बेंचमार्क', benchmarkLede: 'अभी ऐप के माध्यम से एक लेबल किया गया परीक्षण सेट चलाता है।', benchmarkRun: 'बेंचमार्क चलाएँ', benchmarkEmpty: 'ताज़ा गणना की गई सटीकता और सुरक्षा नियम देखने के लिए बेंचमार्क चलाएँ।',
      jurisdictionInvariant: 'क्षेत्राधिकार पृथक्करण', citationInvariant: 'उद्धरण अखंडता', violations: 'उल्लंघन', abstentionAccuracyLabel: 'उत्तर-त्याग सटीकता', clarificationAccuracy: 'स्पष्टीकरण सटीकता', citationHitRate: 'उद्धरण हिट दर', benchmarkItemCount: '{n} लेबल किए गए परीक्षण मदों के विरुद्ध गणना की गई।' },
  },
  ta: {
    appName: 'சூத்ரதார',
    tagline: 'ஆயுர்வேதத்திற்கான AI-இயங்கும் அறிவுசார் சொத்து & ஒழுங்குமுறை நுண்ணறிவு',
    team: 'குழு சதுர்யா',
    heroLede:
      'இந்த தளம் ஆயுர்வேத தயாரிப்புகளை பொருந்தும் அறிவுசார் சொத்து ஆட்சிமுறைகள், ஒழுங்குமுறை தேவைகள், அதிகார வரம்பு சார்ந்த விதிகள் மற்றும் அதிகாரப்பூர்வ ஆதாரங்களுடன் இணைக்கிறது.',
    heroCta: 'ஒரு ஆயுர்வேத தயாரிப்பை பகுப்பாய்வு செய்யவும்',
    pipeline: ['தயாரிப்பு', 'வகைப்பாடு', 'IP', 'ஒழுங்குமுறை', 'ஆதாரங்கள்'],

    navAnalyze: 'பகுப்பாய்வு',
    navAbs: 'ABS இணக்கம்',
    navTkdl: 'TKDL சரிபார்ப்பு',
    navEvidence: 'ஆதாரங்கள்',
    navGraph: 'அறிவு வரைபடம்',
    navEval: 'மதிப்பீடு',

    inputLabel: 'உங்கள் ஆயுர்வேத தயாரிப்பு அல்லது IP கேள்வியை விவரிக்கவும்',
    placeholder: 'எ.கா. பாரம்பரிய நூலில் ஏற்கனவே விவரிக்கப்பட்ட ஒரு பாரம்பரிய ஆயுர்வேத சூத்திரமாக்கத்திற்கு நான் காப்புரிமை பெற முடியுமா?',
    micStart: 'குரல் கேள்வியை பதிவு செய்யவும்', micStop: 'பதிவை நிறுத்தவும்', micNotSupported: 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை.', micPermissionDenied: 'மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது — உங்கள் உலாவி அனுமதிகளை சரிபார்க்கவும்.', micTranscribeFailed: 'படியெடுத்தல் சேவையை அடைய முடியவில்லை. பதிலாக உங்கள் கேள்வியை தட்டச்சு செய்யலாம்.', micUnavailableTooltip: 'இந்த வரிசைப்படுத்தலில் குரல் உள்ளீடு இன்னும் கட்டமைக்கப்படவில்லை.',
    readAloudStart: 'பதிலை சத்தமாக படிக்கவும்', readAloudStop: 'படிப்பதை நிறுத்தவும்', readAloudNotSupported: 'இந்த உலாவியில் எழுத்து-முதல்-பேச்சு ஆதரிக்கப்படவில்லை.', readAloudNoAnswer: 'பதிலை சத்தமாக படிக்க முதலில் ஒரு பகுப்பாய்வை இயக்கவும்.',
    analyze: 'பகுப்பாய்வு செய்',
    analyzing: 'பகுப்பாய்வு செய்கிறது…',
    india: 'இந்தியா',
    international: 'சர்வதேசம்',
    disclaimer: 'இது தகவல் மட்டுமே, சட்ட ஆலோசனை அல்ல.',
    classification: 'தயாரிப்பு வகைப்பாடு',
    jurisdiction: 'அதிகார வரம்பு',
    applicableAreas: 'பொருந்தும் IP & ஒழுங்குமுறை பகுதிகள்',
    assessment: 'AI மதிப்பீடு',
    sources: 'ஆதாரங்கள் & மேற்கோள்கள்',
    confidence: 'ஆதார நம்பகத்தன்மை',
    escalate: 'IP வசதியாளருக்கு அனுப்பு',
    needExpert: 'நிபுணர் உதவி தேவையா?',
    detectedLanguage: 'கண்டறியப்பட்ட உள்ளீட்டு மொழி',
    retrievalNote: 'மீட்பிற்காக இயல்பாக்கப்பட்டது',
    evidenceBoundary: 'ஆதார எல்லை',
    evidenceBoundaryBody: 'நம்பகமான பதிலை வழங்க போதுமான அதிகாரப்பூர்வ ஆதாரம் இல்லை.',
    whyAbstained: 'கணினி ஏன் பதிலளிக்க மறுத்தது',
    systemError: 'பகுப்பாய்வு சேவை தற்காலிகமாக கிடைக்கவில்லை. தயவுசெய்து சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',

    evidencePageTitle: 'ஆதார ஆய்வகம்',
    evidencePageLede: 'கடைசி பதில் எங்கிருந்து வந்தது? கீழே உள்ள ஒவ்வொரு ஆதாரமும் உங்கள் சமீபத்திய பகுப்பாய்விற்காக அதிகாரப்பூர்வ கார்பஸிலிருந்து உண்மையில் மீட்கப்பட்டது — இங்கு எதுவும் கற்பனை செய்யப்படவில்லை.',
    evidenceEmpty: 'முதலில் ஒரு பகுப்பாய்வை இயக்கவும் — அந்த கேள்விக்கான மீட்கப்பட்ட ஆதாரங்கள் இங்கே தோன்றும்.',

    graphEmpty: 'அறிவு வரைபட தரவு தற்போது பின்நிலையத்திலிருந்து கிடைக்கவில்லை.',
    evalEmpty: 'இந்த அமர்வில் இதுவரை எந்த கேள்விகளும் பதிவு செய்யப்படவில்லை.',

    absTitle: 'ABS இணக்க சரிபார்ப்பு',
    absLede: 'உயிரியல் பன்முகத்தன்மை சட்டம், CBD மற்றும் நகோயா நெறிமுறையின் கீழ் அணுகல்-மற்றும்-பயன்-பகிர்வு கடமைகளை ஒரு கேள்வி தூண்டுவதற்கான வாய்ப்பு உள்ளதா என்பதை சரிபார்க்கிறது — மேலும் அதற்கு என்ன ஆதாரம் ஆதரவளிக்கிறது.',
    absPlaceholder: 'எ.கா. இந்தியாவின் ஒரு குறிப்பிட்ட பகுதியிலிருந்து பெறப்பட்ட உயிரியல் வளத்தைப் பயன்படுத்தி ஒரு சூத்திரமாக்கத்தை வணிகமயமாக்க விரும்புகிறோம்',
    absButton: 'ABS இணக்கத்தை சரிபார்க்கவும்',
    absEmpty: 'ABS சரிபார்ப்புப் பட்டியலைக் காண மேலே தயாரிப்பு அல்லது மூலத் தோற்றக் காட்சியை விவரிக்கவும்.',
    absNotTriggered: 'இந்த கேள்விக்கு தெளிவான அணுகல்-மற்றும்-பயன்-பகிர்வு சமிக்ஞை எதுவும் கிடைக்கவில்லை. இது ABS-ஐ முற்றிலும் நிராகரிக்காது — மேலும் குறிப்பிட்ட சரிபார்ப்பிற்கு உயிரியல் வளத்தையும் அதன் தோற்றத்தையும் விவரிக்கவும்.',

    tkdlTitle: 'TKDL / முன் கலை சரிபார்ப்பு',
    tkdlLede: 'ஒரு பாரம்பரிய சூத்திரமாக்கத்துடன் தொடர்புடைய பாரம்பரிய அறிவு டிஜிட்டல் நூலக பணிப்பாய்வைக் குறிக்கிறது, மேலும் கணினி கண்டறிந்த முன் கலை ஆதாரங்களைக் காட்டுகிறது.',
    tkdlPlaceholder: 'எ.கா. இந்த சூத்திரமாக்கம் ஏற்கனவே ஒரு பாரம்பரிய நூலில் பாரம்பரிய அறிவாக பதிவு செய்யப்பட்டுள்ளதா?',
    tkdlButton: 'TKDL / முன் கலையை சரிபார்க்கவும்',
    tkdlEmpty: 'பாரம்பரிய அறிவு குறிப்பையும் தொடர்புடைய ஆதாரங்களையும் காண மேலே சூத்திரமாக்கத்தை விவரிக்கவும்.',
    tkdlNotTriggered: 'இந்த கேள்விக்கு பாரம்பரிய அறிவு குறிப்பு உருவாக்கப்படவில்லை — இது பாரம்பரிய/பொதுவானதாக வகைப்படுத்தப்படாமல் இருக்கலாம், அல்லது TK-தொடர்பான ஆதாரம் எதுவும் மீட்கப்படவில்லை.',

    languageEnglish: 'ஆங்கிலம்', languageTelugu: 'தெலுங்கு', languageHindi: 'இந்தி', languageTamil: 'தமிழ்', languageMalayalam: 'மலையாளம்', languageSanskrit: 'சமஸ்கிருதம்', primaryNavigation: 'முதன்மை வழிசெலுத்தல்', loadingAnalysis: 'பகுப்பாய்வு ஏற்றப்படுகிறது',
    analysisHelper: 'தேர்ந்தெடுக்கப்பட்ட அதிகார வரம்பில் ஆதார அடிப்படையிலான பகுப்பாய்வு', jurisdictionPrefix: 'அதிகார வரம்பு',
    clarificationCategories: ['பாரம்பரிய / பொது மருந்து', 'காப்புரிமை / தனியுரிம மருந்து', 'புதிய / பாரம்பரியமற்ற மருந்து', 'ஃபைட்டோஃபார்மாசூட்டிகல்', 'ஆயுர்வேத-ஆஹார் / நியூட்ராசூட்டிகல்', 'அழகுசாதனம்'],
    paraphraseVerified: 'Groq மூலம் உருவாக்கப்பட்டது · மேற்கோள்கள் சரிபார்க்கப்பட்டன', translationUnavailableAnswer: 'மொழிபெயர்ப்பு சேவை தற்போது கிடைக்கவில்லை — ஆங்கில பதில் காட்டப்படுகிறது.',
    tkPointer: 'பாரம்பரிய அறிவு / முன் கலை குறிப்பு', absConsiderations: 'சாத்தியமான ABS பரிசீலனைகள்',
    regulatoryPathway: 'உசாவல் ஒழுங்குமுறை பாதை',
    pathwayDisclaimer: 'இது ஒரு உசாவல் நிர்வாக வரிசை மட்டுமே — சட்ட ஆலோசனை அல்ல, எந்த முடிவுக்கும் உத்தரவாதம் அல்ல. தற்போதைய படிவங்கள், கட்டணங்கள் மற்றும் காலவரையறைகளை தொடர்புடைய அதிகாரத்துடன் உறுதிப்படுத்தவும்.',
    tkResemblance: 'அறியப்பட்ட பாரம்பரிய சூத்திரமாக்கங்களுடன் ஒற்றுமை',
    tkResemblanceNote: 'நன்கு ஆவணப்படுத்தப்பட்ட பாரம்பரிய சூத்திரமாக்கங்களின் ஒரு சிறிய குறிப்பு தொகுப்புடன் உரை ஒற்றுமை — இது விளக்கத்திற்கானது மட்டுமே, உண்மையான TKDL தேடலுக்கு மாற்றல்ல.',
    downloadPosture: 'IP நிலை சுருக்கத்தை பதிவிறக்கவும் (PDF)',
    absChecklist: { biologicalResource: 'உயிரியல் வளம் ஈடுபட்டுள்ளது', provenance: 'மூலம்/தோற்றம் அடையாளம் காணப்பட்டது', framework: 'தொடர்புடைய ABS கட்டமைப்பு அடையாளம் காணப்பட்டது', source: 'ஆதரவு ஆதாரம் மீட்கப்பட்டது' },
    confidenceSupport: 'தக்கவைக்கப்பட்ட ஆதாரங்கள் இந்த பகுப்பாய்வை எவ்வளவு வலுவாக ஆதரிக்கின்றன', compositeConfidence: 'கூட்டு நம்பகத்தன்மை', confidenceScale: 'நம்பகத்தன்மை அளவுகோல்',
    confidenceFactors: { retrieval_relevance: 'மீட்பு பொருத்தம்', source_count_factor: 'ஆதார எண்ணிக்கை', source_authority: 'ஆதார அதிகாரம்', agreement: 'களப் பொருந்தம்', classification_confidence: 'வகைப்பாடு நம்பகத்தன்மை' },
    confidenceNote: 'இந்த பகுப்பாய்வால் உண்மையில் உருவாக்கப்பட்ட மீட்பு மற்றும் வகைப்பாடு சமிக்ஞைகளிலிருந்து கூட்டு மதிப்பெண் கணக்கிடப்படுகிறது — இது ஒரு கற்பனையான துல்லிய எண் அல்ல.',
    translationUnavailableMessage: 'மொழிபெயர்ப்பு சேவை தற்போது கிடைக்கவில்லை — ஆங்கில செய்தி காட்டப்படுகிறது.', evidenceBoundaryReason: 'தக்கவைக்கப்பட்ட ஆதாரத் தொகுப்பு காலியாக இருந்தது அல்லது அதன் ஒருங்கிணைந்த நம்பகத்தன்மை பாதுகாப்பான-பதில் வரம்பை விட குறைவாக இருந்தது — எனவே கணினி யூகித்து பதிலளிக்க மறுக்கிறது.',
    sourceLabel: 'ஆதாரம்', matchLabel: 'பொருத்தம்', sourceFields: { authority: 'அதிகாரம்', domain: 'களம்', type: 'ஆதார வகை', version: 'பதிப்பு', retrieved: 'மீட்கப்பட்டது', precision: 'துல்லியம்' }, viewSource: 'ஆதாரத்தைக் காண்க',
    builtFor: 'ஆயுஷ் அமைச்சகம் & அகில இந்திய ஆயுர்வேத நிறுவனத்திற்காக கட்டமைக்கப்பட்டது', liveEvidenceTrail: 'ஒரு நேரடி ஆதார பாதை', heroTraceTitle: 'தயாரிப்பிலிருந்து விதிமுறை வரை, சங்கிலி முழுவதும் தெரியும்.', heroTraceBody: 'SUTRADHARA கேள்வியை வகைப்படுத்துகிறது, தொடர்புடைய ஆட்சிமுறைக்கு வழிநடத்துகிறது, மற்றும் ஆதாரத்தை பார்வையில் வைத்திருக்கிறது.', citationGrounded: 'மேற்கோள் அடிப்படையிலான வடிவமைப்பு',
    heroTrace: [{ label: 'தயாரிப்பு கேள்வி', value: 'புதிய செயல்முறையுடன் அஸ்வகந்தா சாறு' }, { label: 'வகைப்பாடு', value: 'ஃபைட்டோஃபார்மாசூட்டிகல் / உயிரியல் வளம்' }, { label: 'ஆதார பாதை', value: 'உயிரியல் பன்முகத்தன்மை சட்டம், 2002 · பிரிவு 7' }], sourceRetained: 'ஆதாரம் தக்கவைக்கப்பட்டது', confidenceHigh: 'நம்பகத்தன்மை: அதிகம்',
    focusedTool: 'கவனம் செலுத்தப்பட்ட ஆராய்ச்சி கருவி', working: 'வேலை செய்கிறது…', absChecklistLabel: 'ABS சரிபார்ப்புப் பட்டியல்', tkdlPointerLabel: 'TKDL குறிப்பு', preview: 'முன்னோட்டம்',
    reviewPathway: 'மனித மதிப்பாய்வு பாதை', escalateTitle: 'IP வசதியாளருக்கு அனுப்பு', escalationDescription: 'ஒரு மனித வசதியாளர் இந்த கேள்வியையும் கீழே மீட்கப்பட்ட ஆதாரங்களையும் மதிப்பாய்வு செய்வார்.', escalationRecorded: 'அனுப்புதல் பதிவு செய்யப்பட்டது.', escalationFollowUp: 'கீழே உள்ள சூழலைப் பயன்படுத்தி ஒரு வசதியாளர் தொடர்பு கொள்வார்.',
    escalationFields: { query: 'கேள்வி', category: 'வகை', jurisdiction: 'அதிகார வரம்பு', areas: 'பகுதிகள்', sources: 'ஆதாரங்கள்' }, noSources: 'எதுவும் இல்லை', contactEmail: 'தொடர்பு மின்னஞ்சல் (விருப்பத்தேர்வு)', emailPlaceholder: 'you@example.com', escalationError: 'அனுப்பும் சேவையை அடைய முடியவில்லை — மீண்டும் முயற்சிக்கவும்.', cancel: 'ரத்து செய்', sending: 'அனுப்புகிறது…', submit: 'சமர்ப்பிக்கவும்',
    graphGrounding: 'பதில் எவ்வாறு அடிப்படையாக்கப்பட்டுள்ளது',
    graphKicker: 'நேரடி தர்க்கம்', graphTitle: 'அறிவு வரைபட ஆய்வகம்', graphLede: 'ஒரு தயாரிப்பு வகையையும் அதிகார வரம்பையும் தேர்ந்தெடுக்கவும் — கீழே உள்ள வரைபடம் ஒவ்வொரு முறையும் உண்மையான கார்பஸிலிருந்து புதிதாக வரையப்படுகிறது, இது ஒரு நிலையான வரைபடம் அல்ல.',
    graphCategoryLabel: 'தயாரிப்பு வகை', graphExportIntentLabel: 'ஏற்றுமதி-தயார்நிலை கிளையை சேர்க்கவும்', graphRunButton: 'வரைபடத்தை கண்டறியவும்', graphStepsTitle: 'தர்க்க பாதை',
    working: 'வேலை செய்கிறது…',
    connectorsTitle: 'கட்டண-ஆதார இணைப்பான்கள்', connectorsLede: 'உங்கள் சொந்த கட்டண IP-தேடல் சந்தாவை இணைக்கவும் — ஒவ்வொரு இணைப்பு, பயன்பாடு மற்றும் ரத்து செய்தலும் பதிவு செய்யப்படுகிறது, மேலும் உங்கள் வெளிப்படையான தேர்வு இல்லாமல் எதுவும் பயன்படுத்தப்படாது.',
    connectorLinkHeading: 'ஒரு சந்தாவை இணைக்கவும்', connectorProviderPlaceholder: 'வழங்குநர் பெயர் (எ.கா. PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'உங்கள் API விசை', connectorLinkButton: 'இணைப்பானை இணைக்கவும்',
    connectorPrivacyNote: 'உங்கள் விசை ஹாஷ் செய்யப்படுகிறது; கடைசி 4 எழுத்துக்கள் மட்டுமே மீண்டும் காட்டப்படும். ரத்து செய்தல் உடனடியாக மேலும் பயன்பாட்டைத் தடுக்கிறது — விதிவிலக்கு இல்லை.',
    connectorsEmpty: 'இந்த அமர்வில் இதுவரை இணைப்பான்கள் எதுவும் இணைக்கப்படவில்லை.', connectorScope: 'எல்லை', connectorLinkedAt: 'இணைக்கப்பட்டது', connectorSelectForTest: 'சோதனை கேள்விக்கு பயன்படுத்தவும்', connectorRevokeButton: 'ரத்து செய்',
    connectorTestHeading: 'இந்த இணைப்பானுடன் ஒரு கேள்வியை இயக்கவும்', connectorTestPlaceholder: 'எ.கா. மஞ்சள் அடிப்படையிலான காயம்-குணப்படுத்தும் சூத்திரமாக்கத்திற்கான முன் கலையைத் தேடவும்', connectorRunTest: 'இணைப்பானுடன் இயக்கவும்',
    navConnectors: 'இணைப்பான்கள்',
    classificationCategories: { 'Classical / Generic Medicine': 'பாரம்பரிய / பொது மருந்து', 'Patent / Proprietary Medicine': 'காப்புரிமை / தனியுரிம மருந்து', 'New / Non-Classical Drug': 'புதிய / பாரம்பரியமற்ற மருந்து', Phytopharmaceutical: 'ஃபைட்டோஃபார்மாசூட்டிகல்', 'Ayurveda-Aahar / Nutraceutical': 'ஆயுர்வேத-ஆஹார் / நியூட்ராசூட்டிகல்', Cosmetic: 'அழகுசாதனம்' }, areaLabels: { Patents: 'காப்புரிமைகள்', 'Geographical Indications': 'புவியியல் குறியீடுகள்', Trademarks: 'வர்த்தக முத்திரைகள்', Copyright: 'பதிப்புரிமை', Designs: 'வடிவமைப்புகள்', 'Trade Secrets': 'வர்த்தக ரகசியங்கள்', 'Plant Variety Protection': 'தாவர இனப் பாதுகாப்பு', 'Traditional Knowledge': 'பாரம்பரிய அறிவு', 'Access-and-Benefit-Sharing': 'அணுகல்-மற்றும்-பயன்-பகிர்வு', 'Drug regulation': 'மருந்து ஒழுங்குமுறை', Advertising: 'விளம்பரம்', Labelling: 'லேபிளிடல்', 'Food / nutraceutical regulation': 'உணவு / நியூட்ராசூட்டிகல் ஒழுங்குமுறை', 'Cosmetic regulation': 'அழகுசாதன ஒழுங்குமுறை' },
    eval: { observability: 'கணினி கண்காணிப்பு', title: 'மதிப்பீட்டு டாஷ்போர்டு', chartLabel: 'நம்பகத்தன்மை வரலாறு விளக்கப்படம்', chartTitle: 'பதிவு செய்யப்பட்ட கேள்விகளில் நம்பகத்தன்மை', observations: 'கவனிப்புகள்', chartEmpty: 'முதல் பகுப்பாய்விற்குப் பிறகு நம்பகத்தன்மை வரலாறு இங்கே தோன்றும்.', queryStart: 'கேள்வி 01', queryLatest: 'சமீபத்திய கேள்வி', totalQueries: 'மொத்தம் பதிவு செய்யப்பட்ட கேள்விகள்', safeAbstention: 'பாதுகாப்பான-பதில்-மறுப்பு விகிதம்', averageConfidence: 'சராசரி நம்பகத்தன்மை', answerAccuracy: 'பதில் துல்லியம்', citationCorrectness: 'மேற்கோள் சரியான தன்மை', classificationAccuracy: 'வகைப்பாடு துல்லியம்', multilingualQuality: 'பன்மொழி பதில் தரம்', pending: 'மதிப்பீடு நிலுவையில் உள்ளது', manualReviewSet: 'மதிப்பீடு நிலுவையில் உள்ளது — சரிபார்க்கப்பட்ட சோதனைத் தொகுப்புடன் மனித மதிப்பாய்வு தேவை', manualReview: 'மதிப்பீடு நிலுவையில் உள்ளது — மனித மதிப்பாய்வு தேவை', emptyTitle: 'உங்கள் ஆதார பாதை இங்கே தொடங்குகிறது.', emptyBody: 'நம்பகத்தன்மை வரலாறு, மேற்கோள் சரிபார்ப்புகள் மற்றும் வகைப்பாடு மதிப்பாய்வை நிரப்ப ஒரு பகுப்பாய்வை இயக்கவும்.', citationReview: 'மேற்கோள் மதிப்பாய்வு', note: 'அமர்வு புள்ளிவிவரங்கள் மட்டுமே — கீழே உள்ள நேரடி பெஞ்ச்மார்க்கை இயக்கவும்.', sessionLede: 'இந்த உலாவி அமர்விலிருந்து மட்டும் உண்மையான எண்ணிக்கைகள் — சேவையகம் மறுதொடக்கமான்போது மீட்டமைக்கப்படும்.',
      benchmarkKicker: 'நேரடியாக கணக்கிடப்பட்டது, தற்காலிகச் சேமிப்பு அல்ல', benchmarkTitle: 'நேரடி மதிப்பீட்டு பெஞ்ச்மார்க்', benchmarkLede: 'இப்போது ஒரு லேபிளிடப்பட்ட சோதனைத் தொகுப்பை பயன்பாட்டின் வழியாக இயக்கி, உண்மையில் என்ன திரும்பி வருகிறது என்பதை புகாரளிக்கிறது.', benchmarkRun: 'பெஞ்ச்மார்க்கை இயக்கவும்', benchmarkEmpty: 'புதிதாக கணக்கிடப்பட்ட துல்லியம் மற்றும் இரண்டு கடுமையான பாதுகாப்பு மாறிலிகளைக் காண பெஞ்ச்மார்க்கை இயக்கவும்.',
      jurisdictionInvariant: 'அதிகார வரம்பு தனிமைப்படுத்தல்', citationInvariant: 'மேற்கோள் ஒருமைப்பாடு', violations: 'மீறல்கள்', abstentionAccuracyLabel: 'பதில்-மறுப்பு துல்லியம்', clarificationAccuracy: 'தெளிவுபடுத்தல் துல்லியம்', citationHitRate: 'மேற்கோள் பொருத்த விகிதம்', benchmarkItemCount: 'data/eval_dataset.json இல் உள்ள {n} லேபிளிடப்பட்ட சோதனை உருப்படிகளுக்கு எதிராக கணக்கிடப்பட்டது.' },
  },
  ml: {
    appName: 'സൂത്രധാര',
    tagline: 'ആയുർവേദത്തിനായുള്ള AI-പ്രവർത്തിത ബൗദ്ധിക സ്വത്തവകാശം & നിയന്ത്രണ ബുദ്ധി',
    team: 'ടീം ചതുര്യ',
    heroLede:
      'ഈ പ്ലാറ്റ്‌ഫോം ആയുർവേദ ഉൽപ്പന്നങ്ങളെ ബാധകമായ ബൗദ്ധിക സ്വത്തവകാശ വ്യവസ്ഥകൾ, നിയന്ത്രണ ആവശ്യകതകൾ, അധികാരപരിധി-നിർദ്ദിഷ്ട നിയമങ്ങൾ, ആധികാരിക തെളിവുകൾ എന്നിവയുമായി ബന്ധിപ്പിക്കുന്നു.',
    heroCta: 'ഒരു ആയുർവേദ ഉൽപ്പന്നം വിശകലനം ചെയ്യുക',
    pipeline: ['ഉൽപ്പന്നം', 'വർഗ്ഗീകരണം', 'IP', 'നിയന്ത്രണം', 'തെളിവുകൾ'],

    navAnalyze: 'വിശകലനം',
    navAbs: 'ABS അനുസരണം',
    navTkdl: 'TKDL പരിശോധന',
    navEvidence: 'തെളിവുകൾ',
    navGraph: 'അറിവ് ഗ്രാഫ്',
    navEval: 'മൂല്യനിർണ്ണയം',

    inputLabel: 'നിങ്ങളുടെ ആയുർവേദ ഉൽപ്പന്നമോ IP ചോദ്യമോ വിവരിക്കുക',
    placeholder: 'ഉദാ. ഒരു പരമ്പരാഗത ഗ്രന്ഥത്തിൽ ഇതിനകം വിവരിച്ചിട്ടുള്ള ഒരു ക്ലാസിക്കൽ ആയുർവേദ ഫോർമുലേഷന് എനിക്ക് പേറ്റന്റ് നേടാൻ കഴിയുമോ?',
    micStart: 'ശബ്ദ ചോദ്യം റെക്കോർഡ് ചെയ്യുക', micStop: 'റെക്കോർഡിംഗ് നിർത്തുക', micNotSupported: 'ഈ ബ്രൗസറിൽ വോയ്സ് ഇൻപുട്ട് പിന്തുണയ്ക്കുന്നില്ല.', micPermissionDenied: 'മൈക്രോഫോൺ ആക്സസ് നിഷേധിച്ചു — നിങ്ങളുടെ ബ്രൗസർ അനുമതികൾ പരിശോധിക്കുക.', micTranscribeFailed: 'ട്രാൻസ്ക്രിപ്ഷൻ സേവനത്തിലേക്ക് എത്താൻ കഴിഞ്ഞില്ല. പകരം നിങ്ങളുടെ ചോദ്യം ടൈപ്പ് ചെയ്യാം.', micUnavailableTooltip: 'ഈ ഡിപ്ലോയ്‌മെന്റിൽ വോയ്സ് ഇൻപുട്ട് ഇതുവരെ കോൺഫിഗർ ചെയ്തിട്ടില്ല.',
    readAloudStart: 'ഉത്തരം ഉച്ചത്തിൽ വായിക്കുക', readAloudStop: 'വായന നിർത്തുക', readAloudNotSupported: 'ഈ ബ്രൗസറിൽ ടെക്സ്റ്റ്-ടു-സ്പീച്ച് പിന്തുണയ്ക്കുന്നില്ല.', readAloudNoAnswer: 'ഉത്തരം ഉച്ചത്തിൽ വായിക്കാൻ ആദ്യം ഒരു വിശകലനം പ്രവർത്തിപ്പിക്കുക.',
    analyze: 'വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു…',
    india: 'ഇന്ത്യ',
    international: 'അന്താരാഷ്ട്രം',
    disclaimer: 'ഇത് വിവരം മാത്രമാണ്, നിയമോപദേശമല്ല.',
    classification: 'ഉൽപ്പന്ന വർഗ്ഗീകരണം',
    jurisdiction: 'അധികാരപരിധി',
    applicableAreas: 'ബാധകമായ IP & നിയന്ത്രണ മേഖലകൾ',
    assessment: 'AI വിലയിരുത്തൽ',
    sources: 'തെളിവുകളും ഉദ്ധരണികളും',
    confidence: 'തെളിവ് വിശ്വാസ്യത',
    escalate: 'IP ഫെസിലിറ്റേറ്ററിലേക്ക് അയക്കുക',
    needExpert: 'വിദഗ്ദ്ധ സഹായം വേണോ?',
    detectedLanguage: 'കണ്ടെത്തിയ ഇൻപുട്ട് ഭാഷ',
    retrievalNote: 'വീണ്ടെടുക്കലിനായി സാധാരണവൽക്കരിച്ചു',
    evidenceBoundary: 'തെളിവ് അതിർത്തി',
    evidenceBoundaryBody: 'വിശ്വസനീയമായ ഉത്തരം നൽകാൻ മതിയായ ആധികാരിക തെളിവുകൾ ഇല്ല.',
    whyAbstained: 'സിസ്റ്റം എന്തുകൊണ്ട് വിട്ടുനിന്നു',
    systemError: 'വിശകലന സേവനം താൽക്കാലികമായി ലഭ്യമല്ല. ദയവായി അൽപ്പസമയത്തിനുശേഷം വീണ്ടും ശ്രമിക്കുക.',

    evidencePageTitle: 'തെളിവ് പര്യവേക്ഷകൻ',
    evidencePageLede: 'അവസാന ഉത്തരം എവിടെ നിന്ന് വന്നു? താഴെയുള്ള ഓരോ ഉറവിടവും നിങ്ങളുടെ ഏറ്റവും പുതിയ വിശകലനത്തിനായി ആധികാരിക കോർപ്പസിൽ നിന്ന് യഥാർത്ഥത്തിൽ വീണ്ടെടുത്തതാണ് — ഇവിടെ ഒന്നും കെട്ടിച്ചമച്ചതല്ല.',
    evidenceEmpty: 'ആദ്യം ഒരു വിശകലനം പ്രവർത്തിപ്പിക്കുക — ആ ചോദ്യത്തിനായി വീണ്ടെടുത്ത ഉറവിടങ്ങൾ ഇവിടെ ദൃശ്യമാകും.',

    graphEmpty: 'അറിവ് ഗ്രാഫ് ഡാറ്റ ഇപ്പോൾ ബാക്കെൻഡിൽ നിന്ന് ലഭ്യമല്ല.',
    evalEmpty: 'ഈ സെഷനിൽ ഇതുവരെ ചോദ്യങ്ങളൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല.',

    absTitle: 'ABS അനുസരണ പരിശോധന',
    absLede: 'ജൈവവൈവിധ്യ നിയമം, CBD, നാഗോയ പ്രോട്ടോക്കോൾ എന്നിവയ്ക്ക് കീഴിൽ ഒരു ചോദ്യം ആക്‌സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ് ബാധ്യതകൾ ഉണർത്താൻ സാധ്യതയുണ്ടോ എന്ന് പരിശോധിക്കുന്നു — അതിനെ പിന്തുണയ്ക്കുന്ന തെളിവ് എന്താണെന്നും.',
    absPlaceholder: 'ഉദാ. ഇന്ത്യയിലെ ഒരു പ്രത്യേക പ്രദേശത്ത് നിന്ന് ലഭിച്ച ജൈവ വിഭവം ഉപയോഗിച്ച് ഒരു ഫോർമുലേഷൻ വാണിജ്യവൽക്കരിക്കാൻ ഞങ്ങൾ ആഗ്രഹിക്കുന്നു',
    absButton: 'ABS അനുസരണം പരിശോധിക്കുക',
    absEmpty: 'ABS ചെക്ക്‌ലിസ്റ്റ് കാണാൻ മുകളിൽ ഉൽപ്പന്നമോ സോഴ്സിംഗ് സാഹചര്യമോ വിവരിക്കുക.',
    absNotTriggered: 'ഈ ചോദ്യത്തിന് വ്യക്തമായ ആക്‌സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ് സൂചന കണ്ടെത്തിയില്ല. ഇത് ABS പൂർണ്ണമായും തള്ളിക്കളയുന്നില്ല — കൂടുതൽ നിർദ്ദിഷ്ട പരിശോധനയ്ക്കായി ജൈവ വിഭവവും അതിന്റെ ഉത്ഭവവും വിവരിക്കുക.',

    tkdlTitle: 'TKDL / മുൻകൂർ-കല പരിശോധന',
    tkdlLede: 'ഒരു ക്ലാസിക്കൽ ഫോർമുലേഷനുമായി ബന്ധപ്പെട്ട പരമ്പരാഗത അറിവ് ഡിജിറ്റൽ ലൈബ്രറി വർക്ക്ഫ്ലോയിലേക്ക് വിരൽ ചൂണ്ടുന്നു, സിസ്റ്റം കണ്ടെത്തിയ മുൻകൂർ-കല ഉറവിടങ്ങൾ ഉയർത്തിക്കാട്ടുന്നു.',
    tkdlPlaceholder: 'ഉദാ. ഈ ഫോർമുലേഷൻ ഇതിനകം ഒരു ക്ലാസിക്കൽ ഗ്രന്ഥത്തിൽ പരമ്പരാഗത അറിവായി രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?',
    tkdlButton: 'TKDL / മുൻകൂർ-കല പരിശോധിക്കുക',
    tkdlEmpty: 'പരമ്പരാഗത അറിവ് സൂചകവും അനുബന്ധ ഉറവിടങ്ങളും കാണാൻ മുകളിൽ ഫോർമുലേഷൻ വിവരിക്കുക.',
    tkdlNotTriggered: 'ഈ ചോദ്യത്തിന് പരമ്പരാഗത അറിവ് സൂചകം സൃഷ്ടിച്ചില്ല — ഇത് ക്ലാസിക്കൽ/ജനറിക് ആയി വർഗ്ഗീകരിച്ചിട്ടില്ലായിരിക്കാം, അല്ലെങ്കിൽ TK-ബന്ധപ്പെട്ട ഉറവിടമൊന്നും വീണ്ടെടുത്തിട്ടില്ല.',

    languageEnglish: 'ഇംഗ്ലീഷ്', languageTelugu: 'തെലുങ്ക്', languageHindi: 'ഹിന്ദി', languageTamil: 'തമിഴ്', languageMalayalam: 'മലയാളം', languageSanskrit: 'സംസ്കൃതം', primaryNavigation: 'പ്രാഥമിക നാവിഗേഷൻ', loadingAnalysis: 'വിശകലനം ലോഡ് ചെയ്യുന്നു',
    analysisHelper: 'തിരഞ്ഞെടുത്ത അധികാരപരിധിയിലുടനീളമുള്ള തെളിവ്-അധിഷ്ഠിത വിശകലനം', jurisdictionPrefix: 'അധികാരപരിധി',
    clarificationCategories: ['ക്ലാസിക്കൽ / ജനറിക് മരുന്ന്', 'പേറ്റന്റ് / ഉടമസ്ഥാവകാശ മരുന്ന്', 'പുതിയ / ക്ലാസിക്കൽ അല്ലാത്ത മരുന്ന്', 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ', 'ആയുർവേദ-ആഹാർ / ന്യൂട്രാസ്യൂട്ടിക്കൽ', 'കോസ്മെറ്റിക്'],
    paraphraseVerified: 'Groq വഴി പുനർരൂപീകരിച്ചു · ഉദ്ധരണികൾ പരിശോധിച്ചു', translationUnavailableAnswer: 'വിവർത്തന സേവനം ഇപ്പോൾ ലഭ്യമല്ല — ഇംഗ്ലീഷ് ഉത്തരം കാണിക്കുന്നു.',
    tkPointer: 'പരമ്പരാഗത അറിവ് / മുൻകൂർ-കല സൂചകം', absConsiderations: 'സാധ്യതയുള്ള ABS പരിഗണനകൾ',
    regulatoryPathway: 'സൂചക നിയന്ത്രണ പാത',
    pathwayDisclaimer: 'ഇത് ഒരു സൂചക ഭരണപരമായ ക്രമം മാത്രമാണ് — നിയമോപദേശമല്ല, ഒരു ഫലത്തിന്റെയും ഉറപ്പുമല്ല. നിലവിലെ ഫോമുകൾ, ഫീസുകൾ, സമയക്രമങ്ങൾ എന്നിവ ബന്ധപ്പെട്ട അധികാരിയുമായി സ്ഥിരീകരിക്കുക.',
    tkResemblance: 'അറിയപ്പെടുന്ന ക്ലാസിക്കൽ ഫോർമുലേഷനുകളോടുള്ള സാമ്യം',
    tkResemblanceNote: 'നന്നായി രേഖപ്പെടുത്തിയ ക്ലാസിക്കൽ ഫോർമുലേഷനുകളുടെ ഒരു ചെറിയ റഫറൻസ് സെറ്റുമായുള്ള ടെക്സ്റ്റ് സാമ്യം — ഇത് ദൃഷ്ടാന്തപരം മാത്രമാണ്, യഥാർത്ഥ TKDL തിരയലിന് പകരമല്ല.',
    downloadPosture: 'IP സ്ഥിതി സംഗ്രഹം ഡൗൺലോഡ് ചെയ്യുക (PDF)',
    absChecklist: { biologicalResource: 'ജൈവ വിഭവം ഉൾപ്പെട്ടിരിക്കുന്നു', provenance: 'ഉറവിടം/ഉത്ഭവം തിരിച്ചറിഞ്ഞു', framework: 'ബന്ധപ്പെട്ട ABS ചട്ടക്കൂട് തിരിച്ചറിഞ്ഞു', source: 'പിന്തുണയ്ക്കുന്ന ഉറവിടം വീണ്ടെടുത്തു' },
    confidenceSupport: 'നിലനിർത്തിയ ഉറവിടങ്ങൾ ഈ വിശകലനത്തെ എത്രത്തോളം ശക്തമായി പിന്തുണയ്ക്കുന്നു', compositeConfidence: 'സംയോജിത വിശ്വാസ്യത', confidenceScale: 'വിശ്വാസ്യത സ്കെയിൽ',
    confidenceFactors: { retrieval_relevance: 'വീണ്ടെടുക്കൽ പ്രസക്തി', source_count_factor: 'ഉറവിട എണ്ണം', source_authority: 'ഉറവിട അധികാരം', agreement: 'ഡൊമെയ്ൻ യോജിപ്പ്', classification_confidence: 'വർഗ്ഗീകരണ വിശ്വാസ്യത' },
    confidenceNote: 'ഈ വിശകലനം യഥാർത്ഥത്തിൽ നിർമ്മിച്ച വീണ്ടെടുക്കൽ, വർഗ്ഗീകരണ സൂചനകളിൽ നിന്ന് സംയോജിത സ്കോർ കണക്കാക്കുന്നു — ഇത് ഒരു കെട്ടിച്ചമച്ച കൃത്യതാ കണക്കല്ല.',
    translationUnavailableMessage: 'വിവർത്തന സേവനം ഇപ്പോൾ ലഭ്യമല്ല — ഇംഗ്ലീഷ് സന്ദേശം കാണിക്കുന്നു.', evidenceBoundaryReason: 'നിലനിർത്തിയ തെളിവ് സെറ്റ് ശൂന്യമായിരുന്നു അല്ലെങ്കിൽ അതിന്റെ സംയോജിത വിശ്വാസ്യത സുരക്ഷിത-ഉത്തര പരിധിക്ക് താഴെയായിരുന്നു — അതിനാൽ ഊഹിച്ച് ഉത്തരം നൽകാൻ സിസ്റ്റം വിസമ്മതിക്കുന്നു.',
    sourceLabel: 'ഉറവിടം', matchLabel: 'പൊരുത്തം', sourceFields: { authority: 'അധികാരം', domain: 'ഡൊമെയ്ൻ', type: 'ഉറവിട തരം', version: 'പതിപ്പ്', retrieved: 'വീണ്ടെടുത്തത്', precision: 'കൃത്യത' }, viewSource: 'ഉറവിടം കാണുക',
    builtFor: 'ആയുഷ് മന്ത്രാലയത്തിനും ഓൾ ഇന്ത്യ ഇൻസ്റ്റിറ്റ്യൂട്ട് ഓഫ് ആയുർവേദയ്ക്കും വേണ്ടി നിർമ്മിച്ചത്', liveEvidenceTrail: 'ഒരു തത്സമയ തെളിവ് പാത', heroTraceTitle: 'ഉൽപ്പന്നം മുതൽ വ്യവസ്ഥ വരെ, ശൃംഖല മുഴുവൻ ദൃശ്യമാണ്.', heroTraceBody: 'SUTRADHARA ചോദ്യത്തെ വർഗ്ഗീകരിക്കുന്നു, ബന്ധപ്പെട്ട വ്യവസ്ഥയിലേക്ക് വഴിതിരിച്ചുവിടുന്നു, ഉറവിടം കാഴ്ചയിൽ നിലനിർത്തുന്നു.', citationGrounded: 'ഉദ്ധരണി-അധിഷ്ഠിത രൂപകൽപ്പന',
    heroTrace: [{ label: 'ഉൽപ്പന്ന ചോദ്യം', value: 'പുതിയ പ്രക്രിയയുള്ള അശ്വഗന്ധ സത്ത്' }, { label: 'വർഗ്ഗീകരണം', value: 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ / ജൈവ വിഭവം' }, { label: 'തെളിവ് പാത', value: 'ജൈവവൈവിധ്യ നിയമം, 2002 · വകുപ്പ് 7' }], sourceRetained: 'ഉറവിടം നിലനിർത്തി', confidenceHigh: 'വിശ്വാസ്യത: ഉയർന്നത്',
    focusedTool: 'കേന്ദ്രീകൃത ഗവേഷണ ഉപകരണം', working: 'പ്രവർത്തിക്കുന്നു…', absChecklistLabel: 'ABS ചെക്ക്‌ലിസ്റ്റ്', tkdlPointerLabel: 'TKDL സൂചകം', preview: 'പ്രിവ്യൂ',
    reviewPathway: 'മനുഷ്യ അവലോകന പാത', escalateTitle: 'IP ഫെസിലിറ്റേറ്ററിലേക്ക് അയക്കുക', escalationDescription: 'താഴെയുള്ള വീണ്ടെടുത്ത തെളിവുകൾക്കൊപ്പം ഒരു മനുഷ്യ ഫെസിലിറ്റേറ്റർ ഈ ചോദ്യം അവലോകനം ചെയ്യും.', escalationRecorded: 'എസ്‌കലേഷൻ രേഖപ്പെടുത്തി.', escalationFollowUp: 'താഴെയുള്ള സന്ദർഭം ഉപയോഗിച്ച് ഒരു ഫെസിലിറ്റേറ്റർ തുടർനടപടി സ്വീകരിക്കും.',
    escalationFields: { query: 'ചോദ്യം', category: 'വിഭാഗം', jurisdiction: 'അധികാരപരിധി', areas: 'മേഖലകൾ', sources: 'ഉറവിടങ്ങൾ' }, noSources: 'ഒന്നുമില്ല', contactEmail: 'ബന്ധപ്പെടാനുള്ള ഇമെയിൽ (ഓപ്ഷണൽ)', emailPlaceholder: 'you@example.com', escalationError: 'എസ്‌കലേഷൻ സേവനത്തിലേക്ക് എത്താൻ കഴിഞ്ഞില്ല — ദയവായി വീണ്ടും ശ്രമിക്കുക.', cancel: 'റദ്ദാക്കുക', sending: 'അയക്കുന്നു…', submit: 'സമർപ്പിക്കുക',
    graphGrounding: 'ഉത്തരം എങ്ങനെ അടിസ്ഥാനമാക്കിയിരിക്കുന്നു',
    graphKicker: 'തത്സമയ യുക്തി', graphTitle: 'അറിവ് ഗ്രാഫ് പര്യവേക്ഷകൻ', graphLede: 'ഒരു ഉൽപ്പന്ന വിഭാഗവും അധികാരപരിധിയും തിരഞ്ഞെടുക്കുക — താഴെയുള്ള ഗ്രാഫ് എല്ലാ തവണയും യഥാർത്ഥ കോർപ്പസിൽ നിന്ന് പുതുതായി കണ്ടെത്തുന്നു, ഇത് ഒരു നിശ്ചിത ഡയഗ്രം അല്ല.',
    graphCategoryLabel: 'ഉൽപ്പന്ന വിഭാഗം', graphExportIntentLabel: 'എക്സ്പോർട്ട്-സന്നദ്ധത ശാഖ ഉൾപ്പെടുത്തുക', graphRunButton: 'ഗ്രാഫ് കണ്ടെത്തുക', graphStepsTitle: 'യുക്തി പാത',
    working: 'പ്രവർത്തിക്കുന്നു…',
    connectorsTitle: 'പണമടച്ചുള്ള-ഉറവിട കണക്ടറുകൾ', connectorsLede: 'നിങ്ങളുടെ സ്വന്തം പണമടച്ചുള്ള IP-തിരയൽ സബ്‌സ്‌ക്രിപ്ഷൻ ലിങ്ക് ചെയ്യുക — ഓരോ ലിങ്കും ഉപയോഗവും റദ്ദാക്കലും രേഖപ്പെടുത്തുന്നു, നിങ്ങളുടെ വ്യക്തമായ തിരഞ്ഞെടുപ്പില്ലാതെ ഒന്നും ഉപയോഗിക്കില്ല.',
    connectorLinkHeading: 'ഒരു സബ്‌സ്‌ക്രിപ്ഷൻ ലിങ്ക് ചെയ്യുക', connectorProviderPlaceholder: 'പ്രൊവൈഡർ പേര് (ഉദാ. PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'നിങ്ങളുടെ API കീ', connectorLinkButton: 'കണക്ടർ ലിങ്ക് ചെയ്യുക',
    connectorPrivacyNote: 'നിങ്ങളുടെ കീ ഹാഷ് ചെയ്യുന്നു; അവസാന 4 അക്ഷരങ്ങൾ മാത്രമേ വീണ്ടും കാണിക്കൂ. റദ്ദാക്കുന്നത് ഉടനടി കൂടുതൽ ഉപയോഗം തടയുന്നു — ഒഴിവുകഴിവുകളില്ല.',
    connectorsEmpty: 'ഈ സെഷനിൽ ഇതുവരെ കണക്ടറുകളൊന്നും ലിങ്ക് ചെയ്തിട്ടില്ല.', connectorScope: 'വ്യാപ്തി', connectorLinkedAt: 'ലിങ്ക് ചെയ്തത്', connectorSelectForTest: 'ഒരു ടെസ്റ്റ് ചോദ്യത്തിന് ഉപയോഗിക്കുക', connectorRevokeButton: 'റദ്ദാക്കുക',
    connectorTestHeading: 'ഈ കണക്ടർ ഉപയോഗിച്ച് ഒരു ചോദ്യം പ്രവർത്തിപ്പിക്കുക', connectorTestPlaceholder: 'ഉദാ. മഞ്ഞൾ അടിസ്ഥാനമാക്കിയുള്ള മുറിവ്-ഉണക്കുന്ന ഫോർമുലേഷനുവേണ്ടി മുൻകൂർ-കല തിരയുക', connectorRunTest: 'കണക്ടർ ഉപയോഗിച്ച് പ്രവർത്തിപ്പിക്കുക',
    navConnectors: 'കണക്ടറുകൾ',
    classificationCategories: { 'Classical / Generic Medicine': 'ക്ലാസിക്കൽ / ജനറിക് മരുന്ന്', 'Patent / Proprietary Medicine': 'പേറ്റന്റ് / ഉടമസ്ഥാവകാശ മരുന്ന്', 'New / Non-Classical Drug': 'പുതിയ / ക്ലാസിക്കൽ അല്ലാത്ത മരുന്ന്', Phytopharmaceutical: 'ഫൈറ്റോഫാർമസ്യൂട്ടിക്കൽ', 'Ayurveda-Aahar / Nutraceutical': 'ആയുർവേദ-ആഹാർ / ന്യൂട്രാസ്യൂട്ടിക്കൽ', Cosmetic: 'കോസ്മെറ്റിക്' }, areaLabels: { Patents: 'പേറ്റന്റുകൾ', 'Geographical Indications': 'ഭൂമിശാസ്ത്രപരമായ സൂചനകൾ', Trademarks: 'വ്യാപാരമുദ്രകൾ', Copyright: 'പകർപ്പവകാശം', Designs: 'ഡിസൈനുകൾ', 'Trade Secrets': 'വ്യാപാര രഹസ്യങ്ങൾ', 'Plant Variety Protection': 'സസ്യ ഇനം സംരക്ഷണം', 'Traditional Knowledge': 'പരമ്പരാഗത അറിവ്', 'Access-and-Benefit-Sharing': 'ആക്‌സസ്-ആൻഡ്-ബെനിഫിറ്റ്-ഷെയറിംഗ്', 'Drug regulation': 'മരുന്ന് നിയന്ത്രണം', Advertising: 'പരസ്യം', Labelling: 'ലേബലിംഗ്', 'Food / nutraceutical regulation': 'ഭക്ഷണം / ന്യൂട്രാസ്യൂട്ടിക്കൽ നിയന്ത്രണം', 'Cosmetic regulation': 'കോസ്മെറ്റിക് നിയന്ത്രണം' },
    eval: { observability: 'സിസ്റ്റം നിരീക്ഷണക്ഷമത', title: 'മൂല്യനിർണ്ണയ ഡാഷ്‌ബോർഡ്', chartLabel: 'വിശ്വാസ്യത ചരിത്ര ചാർട്ട്', chartTitle: 'രേഖപ്പെടുത്തിയ ചോദ്യങ്ങളിലെ വിശ്വാസ്യത', observations: 'നിരീക്ഷണങ്ങൾ', chartEmpty: 'ആദ്യ വിശകലനത്തിനുശേഷം വിശ്വാസ്യത ചരിത്രം ഇവിടെ കാണിക്കും.', queryStart: 'ചോദ്യം 01', queryLatest: 'ഏറ്റവും പുതിയ ചോദ്യം', totalQueries: 'ആകെ രേഖപ്പെടുത്തിയ ചോദ്യങ്ങൾ', safeAbstention: 'സുരക്ഷിത-വിരത നിരക്ക്', averageConfidence: 'ശരാശരി വിശ്വാസ്യത', answerAccuracy: 'ഉത്തര കൃത്യത', citationCorrectness: 'ഉദ്ധരണി കൃത്യത', classificationAccuracy: 'വർഗ്ഗീകരണ കൃത്യത', multilingualQuality: 'ബഹുഭാഷാ ഉത്തര ഗുണനിലവാരം', pending: 'മൂല്യനിർണ്ണയം തീർപ്പുകൽപ്പിക്കാത്തതാണ്', manualReviewSet: 'മൂല്യനിർണ്ണയം തീർപ്പുകൽപ്പിക്കാത്തതാണ് — സ്ഥിരീകരിച്ച ടെസ്റ്റ് സെറ്റിനെതിരെ മനുഷ്യ അവലോകനം ആവശ്യമാണ്', manualReview: 'മൂല്യനിർണ്ണയം തീർപ്പുകൽപ്പിക്കാത്തതാണ് — മനുഷ്യ അവലോകനം ആവശ്യമാണ്', emptyTitle: 'നിങ്ങളുടെ തെളിവ് പാത ഇവിടെ ആരംഭിക്കുന്നു.', emptyBody: 'വിശ്വാസ്യത ചരിത്രം, ഉദ്ധരണി പരിശോധനകൾ, വർഗ്ഗീകരണ അവലോകനം എന്നിവ പൂരിപ്പിക്കാൻ ഒരു വിശകലനം പ്രവർത്തിപ്പിക്കുക.', citationReview: 'ഉദ്ധരണി അവലോകനം', note: 'സെഷൻ കണക്കുകൾ മാത്രം — താഴെയുള്ള തത്സമയ ബെഞ്ച്മാർക്ക് പ്രവർത്തിപ്പിക്കുക.', sessionLede: 'ഈ ബ്രൗസർ സെഷനിൽ നിന്ന് മാത്രമുള്ള യഥാർത്ഥ കണക്കുകൾ — സെർവർ പുനരാരംഭിക്കുമ്പോൾ പുനഃസജ്ജമാക്കും.',
      benchmarkKicker: 'തത്സമയം കണക്കാക്കി, കാഷെ ചെയ്തതല്ല', benchmarkTitle: 'തത്സമയ മൂല്യനിർണ്ണയ ബെഞ്ച്മാർക്ക്', benchmarkLede: 'ഇപ്പോൾ ഒരു ലേബൽ ചെയ്ത ടെസ്റ്റ് സെറ്റ് ആപ്പിലൂടെ പ്രവർത്തിപ്പിച്ച് യഥാർത്ഥത്തിൽ എന്താണ് തിരികെ വരുന്നതെന്ന് റിപ്പോർട്ട് ചെയ്യുന്നു.', benchmarkRun: 'ബെഞ്ച്മാർക്ക് പ്രവർത്തിപ്പിക്കുക', benchmarkEmpty: 'പുതുതായി കണക്കാക്കിയ കൃത്യതയും രണ്ട് കർശനമായ സുരക്ഷാ മാറ്റമില്ലായ്മകളും കാണാൻ ബെഞ്ച്മാർക്ക് പ്രവർത്തിപ്പിക്കുക.',
      jurisdictionInvariant: 'അധികാരപരിധി വേർതിരിവ്', citationInvariant: 'ഉദ്ധരണി സമഗ്രത', violations: 'ലംഘനങ്ങൾ', abstentionAccuracyLabel: 'വിരത കൃത്യത', clarificationAccuracy: 'വ്യക്തത കൃത്യത', citationHitRate: 'ഉദ്ധരണി ഹിറ്റ് നിരക്ക്', benchmarkItemCount: 'data/eval_dataset.json ലെ {n} ലേബൽ ചെയ്ത ടെസ്റ്റ് ഇനങ്ങൾക്കെതിരെ കണക്കാക്കി.' },
  },
  sa: {
    appName: 'सूत्रधार',
    tagline: 'आयुर्वेदाय कृत्रिमबुद्धि-चालिता बौद्धिकसम्पत्ति-नियामक-बुद्धिः',
    team: 'चातुर्य-दलम्',
    heroLede:
      'इयं वेदिका आयुर्वेद-उत्पादान् प्रयोज्यैः बौद्धिकसम्पत्ति-व्यवस्थाभिः, नियामक-आवश्यकताभिः, अधिकारक्षेत्र-विशिष्ट-नियमैः, प्रामाणिक-प्रमाणैः च सह संयोजयति।',
    heroCta: 'आयुर्वेद-उत्पादस्य विश्लेषणं कुरुत',
    pipeline: ['उत्पादः', 'वर्गीकरणम्', 'IP', 'नियमनम्', 'प्रमाणानि'],

    navAnalyze: 'विश्लेषणम्',
    navAbs: 'ABS अनुपालनम्',
    navTkdl: 'TKDL परीक्षणम्',
    navEvidence: 'प्रमाणानि',
    navGraph: 'ज्ञान-आरेखः',
    navEval: 'मूल्यांकनम्',

    inputLabel: 'भवतः आयुर्वेद-उत्पादं बौद्धिकसम्पत्ति-प्रश्नं वा वर्णयतु',
    placeholder: 'यथा, परम्परा-ग्रन्थे वर्णितस्य शास्त्रीय-आयुर्वेद-सूत्रीकरणस्य पेटेण्ट् प्राप्तुं शक्नोमि वा?',
    micStart: 'ध्वनि-प्रश्नं अभिलिख्यताम्', micStop: 'अभिलेखनं निरुध्यताम्', micNotSupported: 'अस्मिन् ब्राउज़रे ध्वनि-निवेशः न समर्थितः।', micPermissionDenied: 'माइक्रोफोन-अनुमतिः निराकृता — भवतः ब्राउज़र-अनुमतीः परीक्षताम्।', micTranscribeFailed: 'लिप्यन्तरण-सेवां प्राप्तुं न शक्तम्। भवान् स्वप्रश्नं टङ्कयितुं शक्नोति।', micUnavailableTooltip: 'अस्मिन् नियोजने ध्वनि-निवेशः अद्यापि संरचितः नास्ति।',
    readAloudStart: 'उत्तरं उच्चैः पठ्यताम्', readAloudStop: 'पठनं निरुध्यताम्', readAloudNotSupported: 'अस्मिन् ब्राउज़रे पाठ-वाक्-परिवर्तनं न समर्थितम्।', readAloudNoAnswer: 'उत्तरं उच्चैः पठितुं प्रथमं विश्लेषणं चालयतु।',
    analyze: 'विश्लेषणं कुरुत',
    analyzing: 'विश्लेषणं क्रियते…',
    india: 'भारतम्',
    international: 'अन्तर्राष्ट्रीयम्',
    disclaimer: 'इदं सूचनामात्रम्, न तु विधि-परामर्शः।',
    classification: 'उत्पाद-वर्गीकरणम्',
    jurisdiction: 'अधिकारक्षेत्रम्',
    applicableAreas: 'प्रयोज्याः IP-नियामक-क्षेत्राणि',
    assessment: 'कृत्रिमबुद्धि-मूल्यांकनम्',
    sources: 'प्रमाणानि उद्धरणानि च',
    confidence: 'प्रमाण-विश्वसनीयता',
    escalate: 'IP-सहायकाय प्रेषयतु',
    needExpert: 'विशेषज्ञ-सहायता अपेक्षिता वा?',
    detectedLanguage: 'ज्ञाता निवेश-भाषा',
    retrievalNote: 'पुनःप्राप्त्यर्थं सामान्यीकृतम्',
    evidenceBoundary: 'प्रमाण-सीमा',
    evidenceBoundaryBody: 'विश्वसनीयस्य उत्तरस्य दानाय पर्याप्तं प्रामाणिकं प्रमाणं नास्ति।',
    whyAbstained: 'व्यवस्था कस्मात् विरता',
    systemError: 'विश्लेषण-सेवा साम्प्रतं तात्कालिकरूपेण अनुपलब्धा। कृपया क्षणानन्तरं पुनः प्रयत्नं कुरुत।',

    evidencePageTitle: 'प्रमाण-अन्वेषकः',
    evidencePageLede: 'अन्तिमम् उत्तरं कुतः आगतम्? अधः स्थितानि सर्वाणि प्रमाणानि भवतः नवीनतम-विश्लेषणार्थं प्रामाणिक-कोषात् वस्तुतः पुनःप्राप्तानि — अत्र किमपि कल्पितं नास्ति।',
    evidenceEmpty: 'प्रथमं विश्लेषणं चालयतु — तस्य प्रश्नस्य पुनःप्राप्तानि प्रमाणानि अत्र दृश्यन्ते।',

    graphEmpty: 'ज्ञान-आरेख-दत्तांशः साम्प्रतं पश्चभागात् अनुपलब्धः।',
    evalEmpty: 'अस्मिन् सत्रे अद्यावधि कोऽपि प्रश्नः न लिखितः।',

    absTitle: 'ABS-अनुपालन-परीक्षणम्',
    absLede: 'जैवविविधता-अधिनियमस्य, CBD-स्य, नागोया-प्रोटोकॉलस्य च अधीनं प्रश्नः अभिगमन-लाभ-साझाकरण-दायित्वानि उद्दीपयितुं शक्नोति वा इति परीक्षते — तस्य समर्थने किं प्रमाणम् अस्ति इति च।',
    absPlaceholder: 'यथा, भारतस्य विशिष्ट-प्रदेशात् प्राप्तं जैविक-संसाधनं उपयुज्य सूत्रीकरणस्य वाणिज्यीकरणं वयं इच्छामः',
    absButton: 'ABS-अनुपालनं परीक्षताम्',
    absEmpty: 'ABS-सूचीं द्रष्टुं उपरि उत्पादं स्रोत-परिस्थितिं वा वर्णयतु।',
    absNotTriggered: 'अस्य प्रश्नस्य कृते स्पष्टं अभिगमन-लाभ-साझाकरण-सङ्केतं न प्राप्तम्। एतत् ABS इत्येतत् पूर्णतया न निराकरोति — विशिष्टतर-परीक्षणाय जैविक-संसाधनं तस्य उत्पत्तिं च वर्णयतु।',

    tkdlTitle: 'TKDL / पूर्व-कला-परीक्षणम्',
    tkdlLede: 'शास्त्रीय-सूत्रीकरणेन सम्बद्धं परम्परागत-ज्ञान-डिजिटल-पुस्तकालय-कार्यप्रवाहं सूचयति, व्यवस्थया ज्ञातान् पूर्व-कला-स्रोतान् च प्रदर्शयति।',
    tkdlPlaceholder: 'यथा, इदं सूत्रीकरणं पूर्वमेव कस्मिंश्चित् शास्त्रीय-ग्रन्थे परम्परागत-ज्ञानरूपेण लिखितम् अस्ति वा?',
    tkdlButton: 'TKDL / पूर्व-कलां परीक्षताम्',
    tkdlEmpty: 'परम्परागत-ज्ञान-सूचकं सम्बद्धानि प्रमाणानि च द्रष्टुं उपरि सूत्रीकरणं वर्णयतु।',
    tkdlNotTriggered: 'अस्य प्रश्नस्य कृते परम्परागत-ज्ञान-सूचकं न निर्मितम् — सम्भवतः इदं शास्त्रीय/सामान्यरूपेण न वर्गीकृतम्, अथवा कोऽपि TK-सम्बद्धः स्रोतः न प्राप्तः।',

    languageEnglish: 'आङ्ग्लभाषा', languageTelugu: 'तेलुगुभाषा', languageHindi: 'हिन्दीभाषा', languageTamil: 'तमिऴभाषा', languageMalayalam: 'मलयाळभाषा', languageSanskrit: 'संस्कृतम्', primaryNavigation: 'प्रमुख-सञ्चरणम्', loadingAnalysis: 'विश्लेषणं भारित्यते',
    analysisHelper: 'चयनित-अधिकारक्षेत्रे प्रमाण-आधारितं विश्लेषणम्', jurisdictionPrefix: 'अधिकारक्षेत्रम्',
    clarificationCategories: ['शास्त्रीयम् / सामान्यम् औषधम्', 'पेटेण्ट् / स्वामित्व-औषधम्', 'नूतनम् / अशास्त्रीयम् औषधम्', 'फाइटोफार्मास्युटिकल्', 'आयुर्वेद-आहारः / न्यूट्रास्युटिकल्', 'सौन्दर्यप्रसाधनम्'],
    paraphraseVerified: 'Groq-द्वारा पुनःरचितम् · उद्धरणानि सत्यापितानि', translationUnavailableAnswer: 'अनुवाद-सेवा साम्प्रतं अनुपलब्धा — आङ्ग्लम् उत्तरं दर्श्यते।',
    tkPointer: 'परम्परागत-ज्ञानम् / पूर्व-कला-सूचकम्', absConsiderations: 'सम्भाव्याः ABS-विचारणाः',
    regulatoryPathway: 'सूचक-नियामक-मार्गः',
    pathwayDisclaimer: 'इदं केवलं सूचकं प्रशासनिकं क्रमम् — न विधि-परामर्शः, न च कस्यचित् परिणामस्य आश्वासनम्। वर्तमानानि प्रपत्राणि, शुल्कानि, समयसीमाः च सम्बद्ध-प्राधिकरणेन सह सुनिश्चितं कुरुत।',
    tkResemblance: 'ज्ञात-शास्त्रीय-सूत्रीकरणैः सह साम्यम्',
    tkResemblanceNote: 'सुदस्तावेजीकृतानां शास्त्रीय-सूत्रीकरणानां लघु-निर्देश-समुच्चयेन सह पाठ्य-साम्यम् — इदं केवलं दृष्टान्तार्थम्, न तु वास्तविक-TKDL-अन्वेषणस्य विकल्पः।',
    downloadPosture: 'IP-स्थिति-सारांशं डाउनलोड कुरुत (PDF)',
    absChecklist: { biologicalResource: 'जैविक-संसाधनं सम्मिलितम्', provenance: 'स्रोतः/उत्पत्तिः ज्ञाता', framework: 'सम्बद्धं ABS-ढाँचा ज्ञातम्', source: 'समर्थक-स्रोतः प्राप्तः' },
    confidenceSupport: 'रक्षिताः स्रोतः इदं विश्लेषणं कियत् दृढतया समर्थयन्ति', compositeConfidence: 'सम्मिश्रित-विश्वसनीयता', confidenceScale: 'विश्वसनीयता-मापः',
    confidenceFactors: { retrieval_relevance: 'पुनःप्राप्ति-सङ्गतिः', source_count_factor: 'स्रोत-संख्या', source_authority: 'स्रोत-प्रामाणिकता', agreement: 'क्षेत्र-सहमतिः', classification_confidence: 'वर्गीकरण-विश्वसनीयता' },
    confidenceNote: 'अस्मात् विश्लेषणात् वस्तुतः उत्पन्नैः पुनःप्राप्ति-वर्गीकरण-सङ्केतैः सम्मिश्रित-अङ्कः गण्यते — इदं कल्पितं यथार्थत्व-अङ्कं नास्ति।',
    translationUnavailableMessage: 'अनुवाद-सेवा साम्प्रतं अनुपलब्धा — आङ्ग्लः सन्देशः दर्श्यते।', evidenceBoundaryReason: 'रक्षितं प्रमाण-समुच्चयं रिक्तम् आसीत् अथवा तस्य सम्मिश्रित-विश्वसनीयता सुरक्षित-उत्तर-सीमातः न्यूना आसीत् — अतः व्यवस्था अनुमानेन उत्तरं दातुं निराकरोति।',
    sourceLabel: 'स्रोतः', matchLabel: 'सामञ्जस्यम्', sourceFields: { authority: 'प्राधिकरणम्', domain: 'क्षेत्रम्', type: 'स्रोत-प्रकारः', version: 'संस्करणम्', retrieved: 'प्राप्तम्', precision: 'यथार्थता' }, viewSource: 'स्रोतं पश्यतु',
    builtFor: 'आयुष-मन्त्रालयाय अखिल-भारतीय-आयुर्वेद-संस्थानाय च निर्मितम्', liveEvidenceTrail: 'जीवन्तः प्रमाण-मार्गः', heroTraceTitle: 'उत्पादात् प्रावधानं यावत्, सम्पूर्णा शृङ्खला दृश्यते।', heroTraceBody: 'सूत्रधारः प्रश्नं वर्गीकरोति, सम्बद्धां व्यवस्थां मार्गयति, स्रोतं च दृष्टिगोचरं रक्षति।', citationGrounded: 'उद्धरण-आधारितं रचनम्',
    heroTrace: [{ label: 'उत्पाद-प्रश्नः', value: 'नूतन-प्रक्रियायुक्तः अश्वगन्धा-सारः' }, { label: 'वर्गीकरणम्', value: 'फाइटोफार्मास्युटिकल् / जैविक-संसाधनम्' }, { label: 'प्रमाण-मार्गः', value: 'जैवविविधता-अधिनियमः, २००२ · धारा ७' }], sourceRetained: 'स्रोतः रक्षितः', confidenceHigh: 'विश्वसनीयता: उच्चा',
    focusedTool: 'केन्द्रितं शोध-उपकरणम्', working: 'कार्यं क्रियते…', absChecklistLabel: 'ABS-सूची', tkdlPointerLabel: 'TKDL-सूचकम्', preview: 'पूर्वावलोकनम्',
    reviewPathway: 'मानव-समीक्षा-मार्गः', escalateTitle: 'IP-सहायकाय प्रेषयतु', escalationDescription: 'मानवः सहायकः इमं प्रश्नं अधः प्राप्तानि प्रमाणानि च समीक्षिष्यति।', escalationRecorded: 'प्रेषणं लिखितम्।', escalationFollowUp: 'अधः स्थित-सन्दर्भम् उपयुज्य सहायकः भवन्तं सम्पर्किष्यति।',
    escalationFields: { query: 'प्रश्नः', category: 'वर्गः', jurisdiction: 'अधिकारक्षेत्रम्', areas: 'क्षेत्राणि', sources: 'स्रोतः' }, noSources: 'न किमपि', contactEmail: 'सम्पर्क-विपत्रम् (ऐच्छिकम्)', emailPlaceholder: 'you@example.com', escalationError: 'प्रेषण-सेवां प्राप्तुं न शक्तम् — कृपया पुनः प्रयतताम्।', cancel: 'निरस्यताम्', sending: 'प्रेष्यते…', submit: 'समर्प्यताम्',
    graphGrounding: 'उत्तरं कथं आधारितम्',
    graphKicker: 'जीवन्त-तर्कः', graphTitle: 'ज्ञान-आरेख-अन्वेषकः', graphLede: 'उत्पाद-वर्गं अधिकारक्षेत्रं च चिनुत — अधः स्थितः आरेखः प्रतिवारं वास्तविक-कोषात् नवीनरूपेण रच्यते, इदं स्थिरं चित्रं नास्ति।',
    graphCategoryLabel: 'उत्पाद-वर्गः', graphExportIntentLabel: 'निर्यात-सज्जता-शाखां सम्मिलितं कुरुत', graphRunButton: 'आरेखं अन्विष्यताम्', graphStepsTitle: 'तर्क-मार्गः',
    working: 'कार्यं क्रियते…',
    connectorsTitle: 'सशुल्क-स्रोत-सम्बन्धकाः', connectorsLede: 'भवतः स्वकीयां सशुल्कां IP-अन्वेषण-सदस्यतां संयोजयतु — प्रत्येकं संयोजनं, उपयोगः, निरसनं च लिख्यते, भवतः स्पष्ट-चयनं विना किमपि न उपयुज्यते।',
    connectorLinkHeading: 'सदस्यतां संयोजयतु', connectorProviderPlaceholder: 'प्रदातृ-नाम (यथा, PatSeer, Derwent Innovation)', connectorKeyPlaceholder: 'भवतः API-कुञ्जिका', connectorLinkButton: 'सम्बन्धकं संयोजयतु',
    connectorPrivacyNote: 'भवतः कुञ्जिका हैश् क्रियते; अन्तिमाः ४ अक्षराः एव पुनः दर्श्यन्ते। निरसनं तत्क्षणं अग्रे उपयोगं निरुणद्धि — न कोऽपि अपवादः।',
    connectorsEmpty: 'अस्मिन् सत्रे अद्यावधि कोऽपि सम्बन्धकः न संयोजितः।', connectorScope: 'व्याप्तिः', connectorLinkedAt: 'संयोजितम्', connectorSelectForTest: 'परीक्षण-प्रश्नाय उपयुज्यताम्', connectorRevokeButton: 'निरस्यताम्',
    connectorTestHeading: 'अनेन सम्बन्धकेन एकं प्रश्नं चालयतु', connectorTestPlaceholder: 'यथा, हरिद्रा-आधारित-व्रण-रोपण-सूत्रीकरणाय पूर्व-कलां अन्विष्यताम्', connectorRunTest: 'सम्बन्धकेन सह चालयतु',
    navConnectors: 'सम्बन्धकाः',
    classificationCategories: { 'Classical / Generic Medicine': 'शास्त्रीयम् / सामान्यम् औषधम्', 'Patent / Proprietary Medicine': 'पेटेण्ट् / स्वामित्व-औषधम्', 'New / Non-Classical Drug': 'नूतनम् / अशास्त्रीयम् औषधम्', Phytopharmaceutical: 'फाइटोफार्मास्युटिकल्', 'Ayurveda-Aahar / Nutraceutical': 'आयुर्वेद-आहारः / न्यूट्रास्युटिकल्', Cosmetic: 'सौन्दर्यप्रसाधनम्' }, areaLabels: { Patents: 'पेटेण्ट्स्', 'Geographical Indications': 'भौगोलिक-सूचकाः', Trademarks: 'व्यापार-चिह्नानि', Copyright: 'प्रतिलिप्यधिकारः', Designs: 'अभिकल्पाः', 'Trade Secrets': 'वाणिज्य-रहस्यानि', 'Plant Variety Protection': 'वनस्पति-जाति-रक्षणम्', 'Traditional Knowledge': 'परम्परागतं ज्ञानम्', 'Access-and-Benefit-Sharing': 'अभिगमन-लाभ-साझाकरणम्', 'Drug regulation': 'औषध-नियमनम्', Advertising: 'विज्ञापनम्', Labelling: 'लेबलिंग्', 'Food / nutraceutical regulation': 'खाद्य / न्यूट्रास्युटिकल्-नियमनम्', 'Cosmetic regulation': 'सौन्दर्यप्रसाधन-नियमनम्' },
    eval: { observability: 'व्यवस्था-निरीक्षणीयता', title: 'मूल्यांकन-फलकम्', chartLabel: 'विश्वसनीयता-इतिहास-चित्रम्', chartTitle: 'लिखित-प्रश्नेषु विश्वसनीयता', observations: 'निरीक्षणानि', chartEmpty: 'प्रथम-विश्लेषणानन्तरं विश्वसनीयता-इतिहासः अत्र दृश्यते।', queryStart: 'प्रश्नः ०१', queryLatest: 'नवीनतमः प्रश्नः', totalQueries: 'सर्वे लिखिताः प्रश्नाः', safeAbstention: 'सुरक्षित-विरति-दरः', averageConfidence: 'औसत-विश्वसनीयता', answerAccuracy: 'उत्तर-यथार्थता', citationCorrectness: 'उद्धरण-शुद्धता', classificationAccuracy: 'वर्गीकरण-यथार्थता', multilingualQuality: 'बहुभाषा-उत्तर-गुणता', pending: 'मूल्यांकनं प्रलम्बितम्', manualReviewSet: 'मूल्यांकनं प्रलम्बितम् — सत्यापित-परीक्षण-समुच्चयेन सह मानव-समीक्षा अपेक्षिता', manualReview: 'मूल्यांकनं प्रलम्बितम् — मानव-समीक्षा अपेक्षिता', emptyTitle: 'भवतः प्रमाण-मार्गः अत्र आरभते।', emptyBody: 'विश्वसनीयता-इतिहासं, उद्धरण-परीक्षणानि, वर्गीकरण-समीक्षां च पूरयितुं विश्लेषणं चालयतु।', citationReview: 'उद्धरण-समीक्षा', note: 'केवलं सत्र-आँकडाः — अधः स्थितं जीवन्त-मानदण्डं चालयतु।', sessionLede: 'अस्मात् ब्राउज़र-सत्रात् एव वास्तविकाः गणनाः — सर्वर-पुनरारम्भे पुनः स्थाप्यन्ते।',
      benchmarkKicker: 'जीवन्तरूपेण गणितम्, न तु सञ्चितम्', benchmarkTitle: 'जीवन्त-मूल्यांकन-मानदण्डम्', benchmarkLede: 'साम्प्रतम् एव लेबल-कृतं परीक्षण-समुच्चयं अनुप्रयोगेन चालयित्वा वस्तुतः किं प्रत्यागच्छति इति निवेदयति।', benchmarkRun: 'मानदण्डं चालयतु', benchmarkEmpty: 'नवीन-गणितां यथार्थतां द्वे कठोरे सुरक्षा-नियमे च द्रष्टुं मानदण्डं चालयतु।',
      jurisdictionInvariant: 'अधिकारक्षेत्र-पार्थक्यम्', citationInvariant: 'उद्धरण-सम्पूर्णता', violations: 'उल्लङ्घनानि', abstentionAccuracyLabel: 'विरति-यथार्थता', clarificationAccuracy: 'स्पष्टीकरण-यथार्थता', citationHitRate: 'उद्धरण-सङ्गति-दरः', benchmarkItemCount: 'data/eval_dataset.json इत्यस्मिन् {n} लेबल-कृतेभ्यः परीक्षण-अंशेभ्यः विरुद्धं गणितम्।' },
  },
}
